[Feature Store] Adding query options to `get_online_feature_service`
mlrun/mlrun pull request #1178
Opened 2021-08-02 11:34 UTC by eyalsol

Signed-off-by: Eyal Salomon <eyals@iguazio.com>

2021-08-09 14:51 UTC, dinal commented on mlrun/feature_store/api.py
>      :param run_config:   function and/or run configuration for remote jobs/services
add documentation

2021-08-12 09:20 UTC, dinal approved these changes

2021-08-12 10:21 UTC, Hedingber requested changes
one minor comment

2021-08-12 10:21 UTC, Hedingber commented on mlrun/feature_store/retrieval/online.py
> +    return None
Make this a method of the `FixedWindowType` enum itself, so you would do:
`FixedWindowType. CurrentOpenWindow.to_qbk_fixed_window_type()`

2021-08-12 12:34 UTC, Hedingber commented on mlrun/feature_store/feature_vector.py
> +        return None
If some will add a new FixedWindowType and forget to handle it in this function I want it to explode not to fail quietly (causing hard to debug bugs)
```suggestion
        else:
            raise NotImplementedError(
                f"Provided fixed window type is not supported. fixed_window_type={self}"
            )
```

2021-08-12 13:17 UTC, Hedingber approved these changes

2021-08-12 13:18 UTC, merged