Sklearn and XGboost autologging
mlrun/mlrun pull request #1256
Opened 2021-08-26 14:41 UTC by AlxZed

replaced with #1285

2021-08-29 15:10 UTC, yaronha commented on mlrun/frameworks/_common/pkl_model_server.py
> +        else:
why not just `is_regressor` .. else .. ?

2021-08-29 20:24 UTC, yaronha commented on mlrun/frameworks/sklearn/__init__.py
> +SklearnModelServer = PklModelServer
add comment `# placeholder, SklearnModelServer may deviate from PklModelServer in future ver`

2021-08-29 20:25 UTC, yaronha commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +    Wraps the original .fit() method of the passed model enabling auto-logging.
add: `Base interface for ML frameworks (sklearn, xgb, ..)`

2021-08-29 20:27 UTC, yaronha commented on mlrun/frameworks/sklearn/__init__.py
> +    :param model:       The model to wrap.
add usage example

2021-08-29 20:28 UTC, yaronha commented on mlrun/frameworks/xgboost/__init__.py
> +    :param model:       The model to wrap.
add usage example

2021-08-29 20:33 UTC, yaronha commented on mlrun/frameworks/_common/pkl_model_server.py
> +    """
add doc, mention its used to serve .pkl based models like .. sk..

2021-08-30 13:56 UTC, guy1992l requested changes
`mlrun/frameworks/__init__.py` Shouldn't be deleted.

2021-08-30 13:59 UTC, guy1992l commented on mlrun/frameworks/_common/pkl_model_server.py
> +        be read from the "body" key of the request.
you read from the "inputs" field, not the "body" field

2021-08-30 13:59 UTC, guy1992l commented on mlrun/frameworks/_common/pkl_model_server.py
> +        elif is_regressor(self.model):
why start with elif and not with if? is it working?

2021-08-30 14:01 UTC, guy1992l commented on mlrun/frameworks/_common/pkl_model_server.py
> +    def predict(self, body: dict) -> list:
change the parameter name from body to request

2021-08-30 14:17 UTC, guy1992l commented on mlrun/frameworks/_common/pkl_model_server.py
> +class PklModelServer(V2ModelServer):
Change name to PickleModelServer

2021-08-30 14:17 UTC, guy1992l commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +        :param data: The train_test_split X_train, X_test, y_train, y_test.
you can take the x_train, y_train from the fit method kwargs. remove data and add x_test, y_test instead.

2021-08-30 14:17 UTC, guy1992l commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +                # Original fit method
# Set the 'fit' method to the original one as otherwise pickling would fail

2021-08-30 14:17 UTC, guy1992l commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +        def post_fit(*args, **kwargs):
make it protected, rename to _post_fit

2021-08-30 14:17 UTC, guy1992l commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +            eval_metrics = eval_model_v2(context, data['X_test'], data['y_test'], model)
I suggest rewriting the 'plots.py' file for commonly used graphs and write a logger for scikitlearn models using the new general plots to generate the desired plots per model.

2021-08-30 14:17 UTC, guy1992l commented on mlrun/frameworks/sklearn/__init__.py
> +       """update or add a function object to the project
what are all of these comments below?

2021-08-30 22:51 UTC, yaronha commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +            context.log_model("model",
@AlxZed u need to set all log_model params (training_set, label_column, framework,  algorithm, feature_vector, ..)

see: https://github.com/mlrun/functions/blob/535d3beeb903408af46c48911c30ac8e8d110487/sklearn_classifier/sklearn_classifier.py#L113

2021-08-31 21:57 UTC, yaronha commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +                              parameters=model_parameters,
dont log parameters

2021-08-31 21:59 UTC, yaronha commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +                              training_set=test_set,
u should log the `training_set` not the `test_set` , and make sure u drop the index + set the `label_column` value

2021-08-31 21:59 UTC, yaronha commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +                context.log_dataset('train_set',
do not log the training set

2021-08-31 22:02 UTC, yaronha commented on mlrun/frameworks/ml_base/mlrun_interface.py
> +                if data.get("X_test") is not None:
that means u also dont log the model if the user didnt provide (the optional) test_set ?

2021-09-02 10:28 UTC, closed without merging