[Feature store] make 'name' optional in featureset.add_aggregation
mlrun/mlrun pull request #1494
Opened 2021-11-15 13:42 UTC by katyakats

2021-11-15 15:54 UTC, theSaarco requested changes
I have mostly cosmetic comments, there's one doubt I have on the logic you added - please see the comments.

2021-11-15 15:54 UTC, theSaarco commented on mlrun/feature_store/feature_set.py
> +        name=None,
Why not put it either in the end of params or as the 1st optional parameter? Any reason why this is placed here?

2021-11-15 15:54 UTC, theSaarco commented on tests/system/feature_store/test_feature_store.py
> +            pass
```suggestion
        with pytest.raises(mlrun.errors.MLRunInvalidArgumentError):
            # no name parameter, different period
            quotes_set.add_aggregation("bid", ["max"], "1h", "5m")
```

This is more correct - it ensures we're getting the right exception.

2021-11-15 15:54 UTC, theSaarco commented on tests/system/feature_store/test_feature_store.py
> +        try:
See next comment - use `pytest.raises()`

2021-11-16 15:27 UTC, theSaarco commented on tests/system/feature_store/test_feature_store.py
> +            quotes_set.add_aggregation("bid", ["max"], "1h", "5m")
Now you have this same test twice - I believe you meant to do the 2nd test with a different window?

2021-11-17 12:16 UTC, theSaarco approved these changes
LGTM

2021-11-24 07:12 UTC, katyakats commented
@theSaarco approved this with Shahar

2021-11-24 09:29 UTC, merged