[Runtimes] Limit function's service accounts based on project configuration
mlrun/mlrun pull request #1519
Opened 2021-11-24 14:49 UTC by theSaarco

Up until now there was no mechanism to limit the service account that a user can set on a function (using `function.spec.service_account = '<something>'`. This is a potential security issue, for example if users are utilizing Google workload identity that maps service accounts to Google service accounts.

This PR adds the following mechanism to limit the service accounts:
Use 2 internal project secrets (per project):
* `mlrun.service-accounts.allowed` - a list of allowed service accounts, separated by `,`. For example - `sa1, sa2, sa3`
* `mlrun.service-accounts.default` - a default service account per project. This will be automatically assigned to every function deployed from that function, unless the user manually set a different SA

The logic is as follows:

1. If the allowed SAs list is empty (secret does not exist) - the logic is exactly like today, i.e. there's no restriction on the SAs that the user can assign to a function.
2. If a default SA is provided and a function does not have an SA assigned, then set the default SA to the function. If the function already has a SA, keep it.
3. If the allowed SA list is not empty, then validate that the function's SA exists in the list of allowed SAs. If it is not, fail the submitting/deploying of the function.

It's valid to have a default SA without an allowed list. It's also valid to have an allowed list without a default SA.

Currently this PR only adds the validation side, it does not add MLRun APIs to set the allowed list or the default SA. This will be done in the future once we make a decision on the permissions needed for this API and how this should be managed. This can be utilized by externally creating the relevant secret keys per project (it cannot be done through MLRun's project-secret mechanism, since the secrets are internal secrets and MLRun will block it).

2021-11-25 19:00 UTC, Hedingber requested changes
I think you're missing the implementation for Dask (see the call to `ensure_function_has_auth_set` from `_start_function`)

2021-11-26 15:04 UTC, theSaarco commented on tests/api/api/test_submit.py
> +    get_k8s()._get_project_secrets_raw_data = unittest.mock.Mock(return_value=secrets)
Using it.

2021-11-26 15:04 UTC, theSaarco commented on tests/api/api/test_utils.py
> +    get_k8s()._get_project_secrets_raw_data = orig_function
yep

2021-11-26 15:05 UTC, theSaarco commented on tests/api/utils/test_scheduler.py
> +def mock_secrets_call():
right

2021-11-27 13:25 UTC, Hedingber approved these changes

2021-11-27 13:25 UTC, merged