[API] Add versioning compatibility to server and client
mlrun/mlrun pull request #1635
Opened 2022-01-15 15:51 UTC by Tankilevitch

2022-01-15 22:12 UTC, Hedingber requested changes
Very nice, few minor comments

2022-01-15 22:12 UTC, Hedingber commented on mlrun/db/httpdb.py
> +            :param version: API version
```suggestion
            :param version: API version to use, None (the default) will mean to use the default value from mlconf
```

2022-01-15 22:12 UTC, Hedingber commented on tests/api/api/feature_store/base.py
> +        f"projects/{project_name}/{object_url_name}?partition-by=key&partition-sort-by=updated"
Why you're changing the sort-by ?

2022-01-16 08:11 UTC, Tankilevitch commented on mlrun/api/main.py
> +BASE_VERSIONED_API_PREFIX = (
Maybe the condition is redundant, but I do think `BASE_VERSIONED_API_PREFIX` is required.
I wanted one location where it was configured and all components that needed to know the prefix, such as the paths to the docs and the TestClient, could point to.

2022-01-16 08:32 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +        return api_version_path
I added the `versioned` param to let the function know whether he really wants the unversioned path or if it doesn't matter to him and it wants to get the default from the `api_base_version`. If I understand correctly what you recommend is that the user will define the exact version he wants regardless of the default one?

2022-01-16 20:10 UTC, Hedingber approved these changes

2022-01-16 20:10 UTC, merged