Fix data types diffs get stats table
mlrun/mlrun pull request #1688
Opened 2022-01-30 13:26 UTC by benbd86

changed logic to handle different data types according to schema received from big query response./
supporting the common types:
        "STRING": "object",
        "BOOL": "bool",
        "FLOAT": "float64",
        "INTEGER": pd.Int64Dtype(),
        "TIMESTAMP": "datetime64[ns]",

2022-02-01 13:06 UTC, Hedingber requested changes

2022-02-01 13:06 UTC, Hedingber commented on tests/system/feature_store/test_google_big_query.py
> +def _is_env_params_doesnt_exist() -> bool:
```suggestion
def _are_google_credentials_set() -> bool:
```

2022-02-01 13:06 UTC, Hedingber commented on tests/system/feature_store/test_google_big_query.py
> +    def _big_query_source_test(name: str, source: BigQuerySource, max_results: int):
```suggestion
    def _test_big_query_source(name: str, source: BigQuerySource, max_results: int):
```

2022-02-01 13:06 UTC, Hedingber commented on tests/system/feature_store/test_google_big_query.py
> +#       make sure the file exists under 'tests/system/' and that the test runs on it as working directory.
The test's code creates this file, I think this is redundant no ?

2022-02-01 13:06 UTC, Hedingber commented on tests/system/feature_store/test_google_big_query.py
> +CREDENTIALS_ENV = "GOOGLE_BQ_CREDENTIALS_JSON"
```suggestion
CREDENTIALS_ENV = "MLRUN_SYSTEM_TESTS_GOOGLE_BIG_QUERY_CREDENTIALS_JSON"
```

2022-02-02 00:26 UTC, Hedingber approved these changes

2022-02-02 12:59 UTC, yaronha approved these changes

2022-02-07 17:02 UTC, Hedingber approved these changes

2022-02-07 17:02 UTC, Hedingber commented on automation/system_test/prepare.py
> +@click.argument("google_big_query_credentials_json", type=str, required=True)
Required should be False, please fix in a followup PR

2022-02-07 17:03 UTC, merged