[Feature store] Fix deploy_ingestion_service with aggregations
mlrun/mlrun pull request #1698
Opened 2022-02-01 09:16 UTC by gtopper

ML-1698

2022-02-07 11:16 UTC, urihoenig requested changes

2022-02-07 11:16 UTC, urihoenig commented on mlrun/feature_store/common.py
> +        db.get_feature_set(feature_set.fullname, project, tag)
Per Orit's comment, you have to verify that the featureset has a schema too:
https://jira.iguazeng.com/browse/ML-1698?focusedCommentId=87826&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-87826

2022-02-07 11:27 UTC, gtopper commented on tests/system/feature_store/test_feature_store.py
> +        with pytest.raises(mlrun.errors.MLRunNotFoundError):
As discussed, this is handled in existing code.

2022-02-07 11:27 UTC, gtopper commented on mlrun/feature_store/api.py
> +    verify_feature_set_exists(featureset)
As discussed, this is handled in existing code.

2022-02-08 08:37 UTC, urihoenig approved these changes

2022-02-10 09:40 UTC, Hedingber approved these changes

2022-02-10 09:40 UTC, merged