[Docs] Refresh mlrun_jobs
mlrun/mlrun pull request #1752
Opened 2022-02-15 07:31 UTC by jillnogold

2022-02-15 09:05 UTC, theSaarco requested changes
Looks good, I think the artifact-path section needs some additional explanation, see in the comments.

2022-02-15 09:05 UTC, theSaarco commented on docs/runtimes/mlrun_jobs.ipynb
> +    "Pipeline results are stored at the `artifact_path` location. By default, MLRun adds ```/{{workflow.uid}}``` to the path."
It's a bit different than that - the artifact path for workflows can be either:
1. The artifact_path as passed to the specific call for `run()`, as shown below. In this case, MLRun does not modify the user-provided path
2. The project's artifact_path (set by `project.spec.artifact_path = '<some path>'`)
3. MLRun's default artifact-path, if set.

In the 2nd and 3rd option MLRun will add `/{{workflow.uid}}` to the path as described, but only if the path does not already contain it.

2022-02-15 12:34 UTC, theSaarco approved these changes
LGTM

2022-02-15 16:27 UTC, Hedingber commented
We want to discourage users from using the `%nuclio` magic commands so I think we shouldn't even specify it

2022-02-16 06:57 UTC, jillnogold commented
@theSaarco Please advise on above, how to adjust content for removing nuclio magic

2022-02-16 07:47 UTC, theSaarco commented
@jillnogold - we kept the `%nuclio` reference just as another alternative to specifying requirements, for completeness. I am not overly attached to it, and as @Hedingber mentioned, there is already a better way that we describe here. 
So, I'm ok with removing the `%nuclio` reference here - let's just say that you need to pass requirements through the `code_to_function` API and use the example we already added.

2022-02-16 11:04 UTC, merged