[Feature Store] Performance improvements for preview and hist calculation in Spark engine
mlrun/mlrun pull request #1860
Opened 2022-04-03 07:40 UTC by theSaarco

When ingesting a feature-set using Spark engine, by default the code produces a preview (20 first rows of the data-frame) and histogram (calculated over all the DF) for int & float columns. The existing code was naive in its approach to these calculations, basically running a `select` on the DF for each column, which may result in tens of queries for the calculations.
This poses no issue when the DF is a basic tabular DF, and would complete in negligible time. However, when adding aggregations, these queries are done on the query that calculates the aggregations, which contains summaries and group-by expressions. Running these queries so many time would accumulate to very long execution times.
This PR reduces the amount of queries performed in both of these stages. It uses a single query with `sample` for the preview (not sure why the previous approach was needed, it was needlessly complex). For histogram calculation it basically adds a column per histogram bin, and to protect from the number of columns becoming too large, it puts a limit on the number of histograms calculated per query (500 columns, which are 25 columns since we're using 20 bins per histogram). If there are more fields that need histograms, more queries will be performed. Still, it reduces the number of queries performed by a factor of 25.

This also fixes a bug in the existing preview code that used `zip` to align lists of values, but in the case where there are `nulls` in columns would cause results to be empty - this is always the case when doing aggregations in the usual, emit-per-period mode, since the calculation fields only have values for a given window per row, and if multiple windows are used there are always `null` values in some fields.

2022-04-04 11:15 UTC, gtopper approved these changes

2022-04-04 11:44 UTC, theSaarco commented on mlrun/data_types/spark.py
> +    max_columns_per_query = int(MAX_HISTOGRAM_COLUMNS_IN_QUERY // num_bins)
I thought that too, but you'll be surprised to find out it doesn't. If you do `//` between two floats (or float and int), the result would be a float. See for example: https://stackoverflow.com/questions/1282945/why-does-integer-division-yield-a-float-instead-of-another-integer. 
So, the cast is not redundant.

2022-04-04 11:45 UTC, theSaarco commented on mlrun/data_types/spark.py
> +    # We may need multiple queries here. See above comment for reasoning.
It's the only comment above this one 😄

2022-04-04 12:40 UTC, Hedingber requested changes

2022-04-04 12:40 UTC, Hedingber commented on mlrun/data_types/spark.py
> +MAX_HISTOGRAM_COLUMNS_IN_QUERY = 500
make it configurable ?

2022-04-05 13:26 UTC, Hedingber approved these changes

2022-04-05 13:26 UTC, merged