Target Path Object Creation Validation
mlrun/mlrun pull request #1886
Opened 2022-04-10 14:07 UTC by benbd86

Validating creation of TargetPathObject - should contain {run_id} only when run_id defined.

2022-04-10 14:12 UTC, theSaarco approved these changes
Looks good - should probably consider any specific tests you want to add here, specifically the case you added where there's a place-holder but no run-id.

2022-04-10 15:06 UTC, benbd86 commented
Tests were added

2022-04-11 10:35 UTC, Hedingber requested changes

2022-04-11 10:35 UTC, Hedingber commented on tests/system/feature_store/test_feature_store.py
> +            assert mlrun.model.RUN_ID_PLACE_HOLDER not in tp_obj.get_absolute_path()
Maybe I'm missing something but it doesn't seem like you're actually doing something here that require a system, therefore no reason for this to be a system test
Move to `tests/test_model.py`

2022-04-11 13:59 UTC, Hedingber approved these changes

2022-04-11 14:04 UTC, merged