[Docs] Add dataframe, Snowflake, Azure examples, and minor text edits
mlrun/mlrun pull request #1950
Opened 2022-05-10 11:19 UTC by jillnogold

2022-05-12 08:07 UTC, theSaarco requested changes
Reviewed - some items still need work, especially note the Azure example which has some issues in it.

2022-05-12 08:07 UTC, theSaarco commented on docs/feature-store/using-spark-engine.md
> +fstore.ingest(feature_set, source, run_config=run_config, spark_context=spark_service_name)
This example is missing Azure credentials setting. The code should either show how to set credentials (like in the S3 example) or at least note that it's assumed that the correct env variables were set using project-secrets beforehand. This is the same as in the S3 example above.

2022-05-15 05:51 UTC, jillnogold commented on docs/feature-store/using-spark-engine.md
> +For Spark to work with S3, it requires several properties to be set. Spark over S3 can be executed both remotely and locally. The following example writes a
added

2022-05-17 05:35 UTC, theSaarco requested changes
Almost there - a few more changes needed.

2022-05-17 05:35 UTC, theSaarco commented on docs/feature-store/using-spark-engine.md
> +import mlrun.feature_store as fs
I think you misread my previous comment - I just meant for the code markers to be at the end of code. These lines belong at the beginning of the code. However, as noted in other comments - the 2nd line is redundant, just move the `import mlrun` line to the beginning.

2022-05-17 05:35 UTC, theSaarco commented on docs/feature-store/using-spark-engine.md
> +    password="nnnnnn",
```suggestion
    user="<username>",
    password="<password>",
```

If we're using it for the `<url>` parameter, might just as well stick to the convention.

2022-05-17 05:35 UTC, theSaarco commented on docs/feature-store/using-spark-engine.md
> +import mlrun.feature_store as fstore
This line is redundant assuming we return the `import mlrun.feature_store as fs` line to where it belongs. 
However, My suggestion is to do the following:
* Only keep this line (remove the `import mlrun.feature_store as fs` line altogether)
* Make sure only `fstore.` is used - there's a single place to change - see next comment.

2022-05-17 05:35 UTC, theSaarco commented on docs/feature-store/using-spark-engine.md
> +feature_set = fs.FeatureSet("rides7", entities=[fs.Entity("ride_id")], engine="spark", timestamp_key="key")
```suggestion
feature_set = fstore.FeatureSet("rides7", entities=[fstore.Entity("ride_id")], engine="spark", timestamp_key="key")
```

2022-05-17 11:24 UTC, jillnogold commented
@theSaarco - good to go now?

2022-05-17 11:29 UTC, theSaarco approved these changes
LGTM now.

2022-05-17 11:49 UTC, Hedingber approved these changes

2022-05-17 11:49 UTC, merged