[Feature Store] Fix iso conversion on parquet source
mlrun/mlrun pull request #1989
Opened 2022-05-23 09:08 UTC by benbd86

Handle issues with conversion on datetime received from java in iso format.
Try conversion of both java and python iso formats.

[ML-1133](https://jira.iguazeng.com/browse/ML-1133)

2022-05-25 07:20 UTC, gtopper commented on mlrun/datastore/sources.py
> +            if time.endswith("Z"):
I think it makes more sense to first drop a trailing Z if necessary and then parse. Then there is no error handling to consider.

2022-05-25 07:23 UTC, gtopper commented on mlrun/datastore/sources.py
> +            # check if java's iso format if so remove the Z from the end and try again
There is no such thing as "java's iso format" 😅

2022-05-25 08:25 UTC, gtopper commented on mlrun/datastore/sources.py
> +            if time.endswith("Z"):
Also, shouldn't we transform `Z` to `+00:00` rather than just erase it?

2022-05-26 13:49 UTC, gtopper approved these changes

2022-05-29 13:28 UTC, Hedingber requested changes

2022-05-29 13:28 UTC, Hedingber commented on tests/system/feature_store/test_feature_store.py
> +    @pytest.mark.parametrize(
I don't see a reason for this test to be a system test (expensive/slow) and not a unit test (cheap/fast)

2022-05-29 13:28 UTC, Hedingber commented on tests/system/feature_store/test_feature_store.py
> +        def actual_test(time_for_source, is_through_init, time_delta):
If there's no more specific name then just the name of the test function simply go with (prefix underscore) `_test_parquet_source_with_iso_start_or_end_time`

2022-05-29 14:48 UTC, Hedingber approved these changes

2022-05-29 14:48 UTC, merged