[runtimes] Ml 1373 - Validate that the service really exists and raise an error if not.
mlrun/mlrun pull request #1992
Opened 2022-05-23 09:24 UTC by davesh0812

2022-05-26 11:57 UTC, guy1992l requested changes
Small changes and its perfect. Ask Hedi to look into the service check and use `git checkout` on `mlrun/feature_store/steps.py` to remove it from this commit.

2022-05-26 11:57 UTC, guy1992l commented on mlrun/k8s_utils.py
> +                and "meta.helm.sh/release-name" in item.metadata.annotations
please add some comments so one who is not familiar with how services are stored in Kubernetes will understand how you checked the name exists (what is release name, paste an example how it looks like in the yaml for example)

2022-05-26 11:57 UTC, guy1992l commented on mlrun/k8s_utils.py
> +                if name == item.metadata.annotations["meta.helm.sh/release-name"]:
you can simply add it the the list of 'and's in the first if. And is checked from left to right and the first to return False will stop the check so if the `"meta.helm.sh/release-name"` key is not in the dictionary the `name == item.metadata.annotations["meta.helm.sh/release-name"]` won't be checked.

2022-05-26 11:57 UTC, guy1992l commented on mlrun/k8s_utils.py
> +                and "meta.helm.sh/release-name" in item.metadata.annotations
Verify with @Hedingber its a valid / robust check. Maybe add a configuration from `mlconf` if its not something set in stone.

2022-05-26 11:57 UTC, guy1992l commented on mlrun/runtimes/remotesparkjob.py
> +                f"spark service named {spark_service} doesn't exist"
Be nicer in the error message :)

`The spark service provided '{}' does not exist. Please notice the name should be given as it is shown in the Iguazio UI.`

Something like that

2022-05-29 23:06 UTC, yaronha commented on mlrun/runtimes/remotesparkjob.py
> +        # check for existence of spark_services
@guy1992l @davesh0812 the test should not be in the client (w/o k8s access), rather in the server side when this value is used for deployment (and there is k8s)

2022-06-13 13:22 UTC, closed without merging