[Feature Store] Updated return_df behavior in ingest
mlrun/mlrun pull request #2005
Opened 2022-05-31 11:23 UTC by yonishelach

[ML-1488](https://jira.iguazeng.com/browse/ML-1488)

2022-05-31 13:33 UTC, guy1992l requested changes

2022-06-06 12:27 UTC, yonishelach commented on mlrun/feature_store/api.py
> +    calculated_df = return_df or infer_stats != InferOptions.Null
added

2022-06-13 08:02 UTC, Tankilevitch requested changes
Tests needs to be added.

2022-06-13 09:31 UTC, yonishelach commented on mlrun/feature_store/api.py
> +                          (As long as mlrun_context is not given)
sure, fixed

2022-08-17 09:27 UTC, gtopper requested changes
Fails CI. Please rebase your PR on latest development – right now it's based on the code as it was one month ago (!).

2022-08-17 09:27 UTC, gtopper commented on mlrun/feature_store/api.py
> +                          (As long as mlrun_context is not given)
Not really clear what `mlrun_context` has to do with it?

2022-08-22 09:09 UTC, closed without merging