[Scheduler] Add re-routing to chief
mlrun/mlrun pull request #2059
Opened 2022-06-20 05:34 UTC by Tankilevitch

2022-06-21 17:19 UTC, Hedingber requested changes
Looks good overall, pretty minor comments
Amazing test coverage, bravo for doing the import changes

2022-06-21 17:19 UTC, Hedingber commented on mlrun/api/utils/background_tasks.py
>      def _update_background_task(
I don't think it makes sense to add the decorator on private functions, public ones should be enough (relevant in other places as well)

2022-06-21 17:19 UTC, Hedingber commented on mlrun/api/utils/clients/chief.py
> +        request_kwargs = self._resolve_request_kwargs_from_request(request)
I understand it means we'll have `_proxy_request_to_chief` and `_proxy_request_to_chief_async` - sounds reasonable

2022-06-21 17:19 UTC, Hedingber commented on mlrun/api/utils/helpers.py
> +        if mlrun.mlconf.fail_on_running_chief_functions_in_worker_mode == "enabled":
Great thinking for making this configurable 🥇

2022-06-21 17:19 UTC, Hedingber commented on tests/api/api/test_submit.py
> +    assert handler_mock._proxy_request_to_chief.call_count == 1
same

2022-06-22 04:55 UTC, Tankilevitch commented on mlrun/api/utils/background_tasks.py
> +    @mlrun.api.utils.helpers.run_on_chief_only
right, ensure sounds better, changed.

2022-06-22 05:17 UTC, Tankilevitch commented on tests/api/api/test_functions.py
> +    assert handler_mock._proxy_request_to_chief.call_count == 1
I am not testing whether the chief can handle the request in this test, the one bellow tests that.
This test purpose it to test the flow logic is correct.

2022-06-22 05:17 UTC, Tankilevitch commented on tests/api/api/test_submit.py
> +    assert handler_mock._proxy_request_to_chief.call_count == 1
same ^.

2022-06-22 05:40 UTC, Tankilevitch commented on mlrun/api/utils/clients/chief.py
>          return future.result()
Changed so the caller will pass the body, no need for using event loops any more.

2022-06-22 10:09 UTC, merged