[Model Monitoring]: Create model monitoring feature set per model endpoint
mlrun/mlrun pull request #2084
Opened 2022-06-27 07:52 UTC by EyalDanieliIgu

Instead of using general model monitoring feature per **project**, we create model monitoring feature set per **model endpoint**. The monitoring graph that was defined in the general monitoring feature set is now converted into a serving graph within the model monitoring stream.
	
**With this new logic:**
- The user can decide for each model endpoint whether to apply model monitoring or not.
- Each model endpoint has a new flag called 'monitoring' (under `model_endpoint.spec.monitoring`). If `model_endpoint.spec.monitoring` is True then once we deploy the model endpoint, we also deploy the model monitoring feature set. The name and the type of each feature is taken from the model object. Note that if it's not exist within the model object, the monitoring feature set will be empty of features. 
- The parquet target files that are generated from the model monitoring stream are now partitioned by model endpoint. In other words, each parquet file is connected to a single model endpoint and includes the relevant schema. It allows the model monitoring batch job to process these parquet files by model endpoint and to avoid unnecessary repetitive analysis.
- After each batch process (hourly job by default), the new model monitoring feature set provides an updated statistics based on the latest batch. 
	 
	
In addition, the following PR also includes a fix for handling the error of deploying model monitoring batch job after it has been already deployed.

2022-07-03 09:11 UTC, yaronha commented on mlrun/api/crud/model_endpoints.py
> +        serving_function_name = model_endpoint.spec.function_uri.replace(
use `parse_versioned_object_uri()` instead

2022-07-03 09:14 UTC, yaronha commented on mlrun/api/crud/model_endpoints.py
> +        feature_set.metadata.project = model_endpoint.metadata.project
i suggest to add `labels` w relevant info e.g. `feature_set.metadata.label["endpoint"] = endpoint_id`

2022-07-03 09:30 UTC, yaronha commented on mlrun/api/crud/model_endpoints.py
> +        if len(model_obj.inputs.to_dict()) > 0:
can simply `len(model_obj.inputs)` or `model_obj.inputs.values()`

2022-07-03 09:31 UTC, yaronha commented on mlrun/api/crud/model_endpoints.py
> +                feature_set.add_feature(
why `to_dict()` vs `items()` ?

2022-07-03 09:44 UTC, yaronha commented on mlrun/model_monitoring/model_monitoring_batch.py
> +                serving_function_name = endpoint.spec.function_uri.replace(
use `parse_versioned_object_uri()` instead

2022-07-03 13:58 UTC, yaronha approved these changes

2022-07-04 13:03 UTC, Tankilevitch requested changes

2022-07-04 13:03 UTC, Tankilevitch commented on mlrun/model_monitoring/helpers.py
> +
You are creating serving graph inside a get function, why?

2022-07-05 09:22 UTC, Tankilevitch requested changes

2022-07-05 09:22 UTC, Tankilevitch commented on mlrun/model_monitoring/helpers.py
> +
Lets change it to apply serving graph

2022-07-05 09:22 UTC, Tankilevitch commented on mlrun/api/crud/model_endpoints.py
> +                )
Lets move it to struct that contains the different modes, so we could refer to the available modes.

2022-07-05 09:22 UTC, Tankilevitch commented on mlrun/api/schemas/model_endpoints.py
> +    monitoring_mode: Optional[str] = "disabled"
Change from str to new Model contains the different monitoring modes.

2022-07-06 04:02 UTC, Tankilevitch commented on mlrun/api/crud/model_endpoints.py
> +        )
move it near the `_submit_run`

2022-07-06 04:02 UTC, Tankilevitch commented on mlrun/model_monitoring/helpers.py
Will have to change the naming of the function

2022-07-06 04:03 UTC, merged