[Projects] Add `ensure_project` to CLI commands
mlrun/mlrun pull request #2094
Opened 2022-06-30 13:16 UTC by Tankilevitch

Contains fixes of:
https://github.com/mlrun/mlrun/pull/2092#pullrequestreview-1023166433
https://github.com/mlrun/mlrun/pull/2063#pullrequestreview-1023170144

Also added fix for release-notes generation to use `git log old_branch..new_branch` instead of `git log old_branch..HEAD`.

2022-07-03 11:17 UTC, Hedingber requested changes

2022-07-03 11:17 UTC, Hedingber commented on mlrun/__main__.py
> +            runtime = func_url_to_runtime(func_url, ensure_project)
You're still ensuring the project only in a specific flow of `run`

2022-07-03 11:17 UTC, Hedingber commented on mlrun/__main__.py
> +        runtime = func_url_to_runtime(func_url, ensure_project)
Same for `deploy`

2022-07-06 07:21 UTC, quaark requested changes

2022-07-06 07:21 UTC, quaark commented on mlrun/api/utils/projects/follower.py
> +        commit_before_get: bool = False,
Why do we default to false here?
And here is the value set to true so we indeed commit before the get?

2022-07-06 07:21 UTC, quaark commented on automation/release_notes/generate.py
> +            "Adam": "quaark",
```suggestion
            "Adam Melnick": "quaark",
```

2022-07-06 07:34 UTC, quaark approved these changes

2022-07-06 16:00 UTC, merged