Kaniko - support ECR
mlrun/mlrun pull request #2100
Opened 2022-07-03 20:18 UTC by AlonMaor14

- Volume aws secret generated from .aws/credentials file to communicate with ECR.
- Use init container with aws cli to create the ECR repository if it does not exist.
- If aws secret was not given - assume instance role

2022-07-05 11:27 UTC, quaark approved these changes
LGTM

2022-07-05 14:09 UTC, Hedingber requested changes

2022-07-05 14:28 UTC, Tankilevitch requested changes

2022-07-06 04:46 UTC, Hedingber commented on mlrun/config.py
> +            "kaniko_registry_provider_auth_secret": "",
Structure for the config should be
```
"function": {
        "spec":{
                "image_pull_secret":{
                    "default": "secret-name"
         },
}
```

2022-07-06 09:02 UTC, AlonMaor14 commented on mlrun/builder.py
> +            )
the 1st one is for the init container
the 2nd one is for the kaniko container

2022-07-06 16:20 UTC, AlonMaor14 commented on mlrun/runtimes/pod.py
> +        )
since we changed the default spec I'm assuming this is no longer relevant

2022-07-06 20:34 UTC, Hedingber approved these changes

2022-07-07 08:16 UTC, Tankilevitch requested changes
Looks good, added minor comments.

2022-07-07 08:16 UTC, Tankilevitch commented on tests/runtimes/test_run.py
> +    expected_runtime["spec"]["image_pull_secret"] = ""
Instead add test that checks the auto enrichment of the default and also the overriding of the default.

2022-07-07 09:16 UTC, Tankilevitch approved these changes

2022-07-07 09:21 UTC, merged