[Feature Store] Fixing bug when using OneHotEncoder on category with int values
mlrun/mlrun pull request #2143
Opened 2022-07-19 08:12 UTC by davesh0812

2022-07-20 11:58 UTC, guy1992l requested changes
minor change and its good to merge in my eyes.

2022-07-27 05:42 UTC, Tankilevitch requested changes
Looks good, added minor comments

2022-07-27 05:42 UTC, Tankilevitch commented on mlrun/feature_store/steps.py
> +from mlrun.errors import MLRunInvalidArgumentError
We are trying to use less `from x import y` but rather use `import x`, this reduces the possibility for circular imports as well as makes it better to understand to where certain classes are part of.
```suggestion
import mlrun.errors
```

2022-07-27 05:42 UTC, Tankilevitch commented on tests/system/feature_store/test_feature_store.py
> +        from mlrun.feature_store.steps import OneHotEncoder
why you import inside the function?

2022-07-27 05:42 UTC, Tankilevitch commented on tests/system/feature_store/test_feature_store.py
> +
```suggestion
        with pytest.raises(ValueError):
            data_set.graph.to(OneHotEncoder(mapping=one_hot_encoder_mapping))
            data_set.set_targets()
            fs.ingest(data_set, data, infer_options=fs.InferOptions.default())
```

2022-07-27 05:42 UTC, Tankilevitch commented on tests/system/feature_store/test_feature_store.py
> +        from mlrun.feature_store.steps import OneHotEncoder
same

2022-08-07 08:12 UTC, Tankilevitch approved these changes

2022-08-07 08:12 UTC, merged