[Runtimes] Add a global config (on server side) for default service account
mlrun/mlrun pull request #2151
Opened 2022-07-20 11:02 UTC by theSaarco

Use case: when deploying in AWS and using instance roles to allow access to S3 resources without need for creds (and also other use-cases which similarly utilize k8s service-accounts), we want every pod that is being launched by MLRun to use a default service account. This default SA should not be user-configurable, but only on the MLRun service configuration.

To support this, added a global config parameter `httpdb.default_service_account` which is empty by default.
The SA logic now becomes:
1. If the job has a SA set in the spec, it is the one used (validated by the allowed-service-accounts per project)
2. Otherwise, if the project has a default SA set in its project-secrets, assign it
3. Else, check if the global SA is set - if it does, assign it

2022-07-20 13:28 UTC, quaark approved these changes

2022-07-20 13:51 UTC, Tankilevitch requested changes
Looks good, minor comment
I think this should be applied also to the builder pods let's add it as well.

2022-07-20 13:51 UTC, Tankilevitch commented on mlrun/config.py
> +        "default_service_account": "",
We introduced new config attribute which is called `function` that inside of it we define `spec` and inside of it the function spec attributes, let's move it to there.

2022-07-21 05:59 UTC, Tankilevitch approved these changes

2022-07-21 05:59 UTC, merged