[SDK] Raise `MLRunInvalidArgumentError` when using `set_env_from_file` if file doesn't exist
mlrun/mlrun pull request #2190
Opened 2022-07-27 11:57 UTC by quaark

Fixes https://jira.iguazeng.com/browse/ML-2384

2022-07-27 15:13 UTC, yaronha commented on mlrun/__init__.py
> +    if not path.isfile(env_file):
need to add: `env_file = os.path.expanduser(env_file)` to resolve `~/` etc.

2022-07-27 15:18 UTC, yaronha commented
worth adding the `env_file = os.path.expanduser(os.environ["MLRUN_ENV_FILE"])` to this as well:

https://github.com/mlrun/mlrun/blob/4403730d0ecd1e8483d52585dd5b326258050fa8/mlrun/config.py#L798

2022-07-27 15:42 UTC, Tankilevitch approved these changes
Looks like there is bug in the docs which states that user need to set `MLRUN_SET_ENV_FILE` rather than `MLRUN_ENV_FILE` can you please add that fix in the PR?

2022-07-31 11:53 UTC, Tankilevitch requested changes

2022-07-31 11:53 UTC, Tankilevitch commented on mlrun/__init__.py
> +        raise MLRunInvalidArgumentError(f"env file {env_file} does not exist")
```suggestion
        raise MLRunNotFoundError(f"env file {env_file} does not exist")
```

2022-08-02 08:50 UTC, merged