[API] Introducing remote debugging
mlrun/mlrun pull request #2232
Opened 2022-08-06 20:29 UTC by liranbg

Instructions is written on `CONTRIBUTING.md` file

2022-08-07 22:29 UTC, Tankilevitch requested changes
This is so useful!! Nicely done, added minor comments

2022-08-07 22:29 UTC, Tankilevitch commented on .github/workflows/build.yaml
> +      if: ${{ matrix.image-name == 'api' }}
We have a mechanism for skipping images, let's add an option to skip `api-dev` as well.

2022-08-07 22:29 UTC, Tankilevitch commented on Makefile
> +MLRUN_API_DEV_IMAGE_NAME_TAGGED := $(MLRUN_API_IMAGE_NAME):$(MLRUN_DOCKER_TAG)-dev
```suggestion
MLRUN_API_DEV_IMAGE_NAME_TAGGED := $(MLRUN_API_IMAGE_NAME)-dev:$(MLRUN_DOCKER_TAG)
```

2022-08-16 09:00 UTC, liranbg commented
continue against development branch @ https://github.com/mlrun/mlrun/pull/2265

2022-08-16 09:00 UTC, closed without merging