[API] Read session verification data from body instead of headers
mlrun/mlrun pull request #2290
Opened 2022-08-23 15:34 UTC by TomerShor

For the response headers to be lighter, user and groups ids are included in the response body from `/sessions/verifications` (see https://github.com/iguazio/zebo/pull/6032).

Change Iguazio authentication to read this info from the body instead of headers, and fallback to the headers in case body is missing.

JIRA: https://jira.iguazeng.com/browse/IG-21097

2022-08-24 06:37 UTC, quaark requested changes
Looks good, a couple of code styling suggestions

2022-08-24 06:37 UTC, quaark commented on mlrun/api/utils/clients/iguazio.py
> +        )
Exactly like you implemented in nuclio, we have in mlrun a `get_in` helper method precisely for cases like this

2022-08-24 06:37 UTC, quaark commented on mlrun/api/utils/clients/iguazio.py
> +
Tried to make this section more concise and cleaner, lmk what yo think
```suggestion
        gids = context_auth.get("group_ids", [])
        
        # fallback to header if no GIDs in the body
        if not gids:
            gids = response.headers.get("x-user-group-ids")
            # "x-user-group-ids" header is a comma separated list of group ids
            if gids:
                gids = gids.split(",")
        
        # some gids can be a comma separated list of group ids (if taken from the headers, the next split will have no effect)
        group_ids = [gid.split(",") for gid in gids]
```

2022-08-24 13:52 UTC, Tankilevitch requested changes
Looks good minor comments

2022-08-24 13:52 UTC, Tankilevitch commented on mlrun/api/utils/clients/iguazio.py
> +        )
Lets add a comment from which Iguazio version we are expecting to receive the `context_auth` in the response body.

2022-08-24 13:52 UTC, Tankilevitch commented on mlrun/api/utils/clients/iguazio.py
> +        )
Also take a look at `if igz_version < semver.VersionInfo.parse` implementation in our code I think that can be suitable here as well.

2022-08-24 13:52 UTC, Tankilevitch commented on mlrun/api/utils/clients/iguazio.py
> +        )
Also explain why the body response has precedence over the header response

2022-08-24 13:52 UTC, Tankilevitch commented on mlrun/api/utils/clients/iguazio.py
> +        # get user and group ids from response body
Maybe instead of this comment you can create a function which it purpose it to resolve params which may have responses in both body and headers.

2022-08-24 14:45 UTC, Tankilevitch requested changes

2022-08-24 14:45 UTC, Tankilevitch commented on mlrun/api/utils/clients/iguazio.py
> +        user_id, group_ids = Client._resolve_user_and_group_ids(response)
I don't know what else will arrive that we might want to resolve from the body in the future so I think it better to give it a name that isn't coupled for `user` and `group_ids`, wdyt? 
```suggestion
        user_id, group_ids = self._resolve_params_from_response_body(response)
```

2022-08-25 08:31 UTC, Tankilevitch approved these changes

2022-08-25 11:09 UTC, quaark requested changes

2022-08-25 11:09 UTC, quaark commented on mlrun/api/utils/clients/iguazio.py
> +        user_id, group_ids = self._resolve_params_from_response_body(response)
These method names aren't really reflective of what they actually do. As `_resolve_params_from_response_body` looks at both headers and body.

Not sure how to rename them though. Maybe `_resolve_params_from_response_headers` can stay as it is but also get the `user_id` and `group_ids` (which might be `None`) and `_resolve_params_from_response_body` can get those only from the body and replace those vars? WDYT? Or different method names.

2022-08-25 11:29 UTC, quaark requested changes
One last thing

2022-08-25 11:29 UTC, quaark commented on mlrun/api/utils/clients/iguazio.py
> +            group_ids = gids
```suggestion
            group_ids,
        ) = self._resolve_params_from_response_headers(response)

        user_id_from_body, group_ids_from_body = self._resolve_params_from_response_body(response)

        # from iguazio version >= 3.5.2, user and group ids are included in the response body
        # if not, get them from the headers
        user_id = user_id_from_body or user_id
        group_ids = group_ids_from_body or group_ids
```

2022-08-25 11:37 UTC, quaark approved these changes

2022-08-25 12:29 UTC, merged