[Runtimes] Add support for commit_id at `pull_at_runtime`
mlrun/mlrun pull request #2320
Opened 2022-08-30 14:13 UTC by Tankilevitch

2022-08-30 14:19 UTC, quaark requested changes
Just one issue

2022-08-30 14:19 UTC, quaark commented on mlrun/utils/clones.py
> +                    f"git:/github.com/example/myproject.git#mybranch#desired-commit-id>"
Using a url in this format (containing 2 `#`s) will have 3 values to unpack when you expect 2 and will raise an exception. Either there's a mistake in the url, or in the handling of the split

2022-08-30 14:19 UTC, quaark commented on mlrun/utils/clones.py
> +        # git:/github.com/example/myproject.git#mybranch#desired-commit-id>.
same ^

2022-08-31 07:46 UTC, quaark approved these changes

2023-02-06 06:58 UTC, Tankilevitch commented
Closing as this was a fix for kaniko 1.7.0 which had a bug and was resolved in 1.8.0

2023-02-06 06:58 UTC, closed without merging