Add dataschema dump
mlrun/mlrun pull request #2370
Opened 2022-09-10 16:48 UTC by george0st

I add new function for dump data schema (feature store schemas) cross all MLRun projects.

I added this function, because we have to collect all master data (cross all company applications) to the one repository/catalog (it is build via e.g. Informatica, Apache Atlas, etc.).

BTW: Where do you see the best place for unit tests? (in 'test\systems\projects' or different?, It is extension of class HTTPRunDB)

2022-09-11 13:54 UTC, Tankilevitch requested changes
Thank you @george0st for you contribution! 
Regarding the unittests, you can add the tests to `tests/rundb/test_unit_httpdb.py` .

2022-09-11 13:54 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +
```suggestion
        # iteration via projects
        for project in self.list_projects():
            project_data_schema = {}
            project_data_schema["project_name"] = prj.name
            if prj.spec.description:
                project_data_schema["project_description"] = project.spec.description
            ...
            dataschema.append(project_data_schema)
```

2022-09-11 13:54 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                        featureset.append({})
same here

2022-09-11 13:54 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                                features.append({})
same

2022-09-11 13:54 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                                entities.append({})
same

2022-09-11 13:54 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +    def dataschema_to_list(self):
```suggestion
    def get_projects_dataschemas(self):
```

2022-09-11 14:50 UTC, theSaarco requested changes
Added some suggestions to make the implementation shorter and clearer, plus some docs changes.

2022-09-11 14:50 UTC, theSaarco commented on mlrun/db/httpdb.py
> +            # or db = mldb.HTTPRunDB()
```suggestion
            db = mlrun.get_run_db()
```

This utility function is better to use than the specific calls used - it already identifies the URL of the target and returns the `HTTPDB` instance needed.

2022-09-11 14:50 UTC, theSaarco commented on mlrun/db/httpdb.py
> +            print(json.dumps(db.dataschema_to_list(),
```suggestion
            print(json.dumps(db.get_projects_dataschemas(),
```

2022-09-11 14:50 UTC, theSaarco commented on mlrun/db/httpdb.py
> +                            entities = []
This entire iteration can also be replaced by something like:
```
entities = fset.spec.entities.to_dict()
```
Or you can also pass to `to_dict()` a set of fields to retrieve, if you're not interested in all the fields:
```
entities = [entity.to_dict(['name', 'description', 'value_type']) for entity in fset.spec.entities]
```
Same is of course true for the features.

2022-09-11 21:04 UTC, george0st commented
@Tankilevitch, please can you check tests (CI/Run Dockerized Tests)

2022-09-13 07:43 UTC, Tankilevitch requested changes
Added some more styling comments, regarding the testing, can you try replicate the way we are mocking the `HTTPRunDB` in the tests above like `test_api_call_enum_conversion` or `test_connection_reset_causes_retries`?

2022-09-13 07:43 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +            dataschema.append(project_data_schema)
matter of style but I think it's better to place that line at the end of each iteration.

2022-09-13 07:43 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                project_data_schema["project_description"] = project.spec.description
for consistency between project schemas I think we should add `project_description` to each project even if its empty.
```suggestion
            project_data_schema["project_description"] = project.spec.description
```

2022-09-13 07:43 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                            ] = feature_set.spec.description
same here

2022-09-13 07:43 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                            ]
same here, it will reduce the need for more indentations and will make the code more cleaner.

2022-09-13 07:43 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                project_data_schema["feature_sets"] = project_feature_sets
```suggestion
            project_data_schema["feature_sets"] = []
```

2022-09-13 07:43 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +                        project_feature_sets.append(featureset_data_schema)
I think this should also be added at the end of each iteration

2022-12-12 19:42 UTC, closed without merging