[Data Store] My Sql - target, source and driver(storey)
mlrun/mlrun pull request #2407
Opened 2022-09-19 12:54 UTC by davesh0812

This pr focus in implementation of source, target and driver for SqlDB.
 SqlDB target can create or read from exists sql collection. The collection is fixed and can't change is schema in the flow.
 SqlDriver is not fully supported in the aggregation query flow.

https://jira.iguazeng.com/browse/ML-2610

2022-10-04 06:12 UTC, gtopper requested changes

2022-10-04 06:12 UTC, gtopper commented on mlrun/datastore/targets.py
> +                metadata.create_all(engine)
I don't think it's right to create a SQL table inside of the constructor. Table creation should happen just before writing. The way it is now, simple creating a `SqlDBTarget` will try to create the SQL table, and that shouldn't happen until the user runs an operation (like `ingest`).

2022-10-04 06:12 UTC, gtopper commented on mlrun/datastore/targets.py
> +            # storage_options=self._get_store().get_storage_options(),
Dead code ☠️

2022-10-04 06:12 UTC, gtopper commented on mlrun/datastore/targets.py
> +        # {‘fail’, ‘replace’, ‘append’} #
Dead code ☠️

2022-10-04 06:12 UTC, gtopper commented on tests/system/feature_store/test_sql_db.py
> +# Copyright 2018 Iguazio
Elsewhere as well of course.

2022-10-04 06:12 UTC, gtopper commented on tests/system/feature_store/test_sql_db.py
> +        sqlite_connection = engine.connect()
Elsewhere as well of course.

2022-10-04 06:12 UTC, gtopper commented on mlrun/datastore/targets.py
> +    mongodb = "mongodb"
What does mongo have to do with this PR though?

2022-10-04 06:12 UTC, gtopper commented on requirements.txt
> +pymongo~=4.1
Also, this is a SQL PR, so not really related to mongo...

2022-10-11 08:07 UTC, davesh0812 commented on mlrun/datastore/storeySourse.py
> +        df = pandas.DataFrame(results)
@gtopper I know it, but in `source.py` in storey you imported it as `import pandas` so I did the same, because one day we will merge it.

2022-10-11 08:30 UTC, davesh0812 commented on mlrun/datastore/targets.py
> +            class_name="storey.NoSqlTarget",
@gtopper NoSqlTarget using the driver(table) for write & read the data.

2022-10-11 08:56 UTC, davesh0812 commented on mlrun/datastore/targets.py
> +                f"mlrunSql://@{db_path}//@{collection_name}"
@gtopper I need it when I load the target.

2022-10-12 08:47 UTC, davesh0812 commented on tests/system/feature_store/test_sql_db.py
> +        "source_name, key", [("stocks", "ticker"), ("trades", "ind"), ("quotes", "ind")]
@gtopper I minimized it, and run tests just on datasets with  different properties.

2022-10-12 08:54 UTC, davesh0812 commented on tests/system/feature_store/test_sql_db.py
> +    return False
I changed it to be more understandable... and it always run

2023-01-03 10:19 UTC, closed without merging