Cli support schedule equal true
mlrun/mlrun pull request #2457
Opened 2022-09-29 12:43 UTC by GiladShapira94

Added an option to support schedule equal true within the mlrun CLI.

The user will need to set a string value for example: `--schedule "true"`.

2022-09-29 13:53 UTC, quaark requested changes
A couple minor comments

2022-09-29 14:36 UTC, GiladShapira94 commented on mlrun/projects/pipelines.py
> +            print(" workflow_spec.schedule_2:", workflow_spec.schedule)
Fixed

2022-10-02 07:11 UTC, Tankilevitch approved these changes
minor suggestion

2022-10-02 07:11 UTC, Tankilevitch commented on mlrun/__main__.py
> +    "for help see: "
```suggestion
    help="to create a schedule define a standard crontab expression string, to use the pre-defined workflow's schedule, set --schedule true."
    "for help see: "
```

2022-10-02 16:29 UTC, merged