[Runtimes] Add with annotations method for runtimes
mlrun/mlrun pull request #2537
Opened 2022-10-31 09:14 UTC by yaelgen

Add with_annotations function so users will be able to set an annotations for the different runtimes:
image

https://jira.iguazeng.com/browse/ML-1495

2022-11-06 19:06 UTC, liranbg approved these changes

2022-11-07 08:04 UTC, Tankilevitch requested changes
Nicely done @yaelgen ! 
super minor comment regarding typehinting :)

2022-11-07 08:04 UTC, Tankilevitch commented on mlrun/runtimes/function.py
> +
```suggestion
    def with_annotations(self, annotations: dict):
        """set a key/value annotations for function"""

```

2022-11-07 08:04 UTC, Tankilevitch commented on mlrun/runtimes/pod.py
> +        """set a key/value annotations in the metadata of the pod"""
same

2022-11-07 09:23 UTC, Tankilevitch approved these changes

2022-11-07 10:12 UTC, merged