[Projects] raise error for workflow scheduling with non-remote project
mlrun/mlrun pull request #2689
Opened 2022-12-07 15:23 UTC by yonishelach

[ML-2931](https://jira.iguazeng.com/browse/ML-2931)

2022-12-07 15:25 UTC, yonishelach commented
The remote checking looks pretty tough to process, should I move it to `MlrunProject` class?

2022-12-07 15:29 UTC, yonishelach commented on mlrun/projects/pipelines.py
> +            raise ValueError(
not sure if the error message is clear enough and if it should be `ValueError`

2022-12-08 08:17 UTC, AlonMaor14 reviewed
Great addition! A few comments / questions.
Also, I would love an explanation for why is this not supported.

2022-12-08 08:25 UTC, AlonMaor14 commented on mlrun/projects/pipelines.py
> +        if (
Also, once you extract the method, please add a docstring of what counts as a remote project (git / archives)

2022-12-08 12:12 UTC, Tankilevitch requested changes
This is missing tests, please add :)

2022-12-08 14:04 UTC, Tankilevitch approved these changes

2022-12-08 14:04 UTC, merged