[Docs] Update docstrings
mlrun/mlrun pull request #2748
Opened 2022-12-13 18:51 UTC by george0st

Update a few doc strings

2022-12-17 09:58 UTC, Tankilevitch requested changes
@george0st Thanks for finding those missing docs, added comments for those params which you defined as TBD

2022-12-17 09:58 UTC, Tankilevitch commented on mlrun/db/httpdb.py
> +        :param params:  TBD.
```suggestion
        :param params:  Rest parameters, passed as a dictionary: ``{"<param-name>": <"param-value">}``
```

2022-12-17 09:58 UTC, Tankilevitch commented on mlrun/model_monitoring/helpers.py
> +    :param auth_info:                   TBD.
```suggestion
    :param auth_info:                   The auth info of the request.
```

2022-12-17 09:58 UTC, Tankilevitch commented on mlrun/run.py
> +    :param allow_empty_resources:   TBD.
```suggestion
    :param mode:    Runtime mode for more details head to `mlrun.new_function`.
    :param allow_empty_resources:   Allow passing non materialized set/vector as input to jobs (Allows to have function which don't depends on having targets, e.g a function which accepts a feature vector uri and generate the offline vector (parquet_ for it if it doesn't exists.
```

2022-12-17 09:58 UTC, Tankilevitch commented on tests/system/demos/horovod/assets/utils_functions.py
> +    :param refresh: TBD.
I think the `refresh` param can be removed it is not being used in the test

2022-12-17 09:58 UTC, Tankilevitch commented on mlrun/runtimes/sparkjob/abstract.py
> +        :param is_kfp:  TBD.
```suggestion
        :param is_kfp:  whether running inside KFP step ( No need to use, being enriched automatically if running inside one .
```

2022-12-22 10:57 UTC, george0st commented
@liranbg , please merge.

2022-12-28 10:06 UTC, Tankilevitch approved these changes

2022-12-28 10:06 UTC, merged