[Model Monitoring] Replace sklearn_classifier with auto_trainer in system tests
mlrun/mlrun pull request #2849
Opened 2023-01-01 10:57 UTC by Eyal-Danieli

`sklearn_classifier` from the functions marketplace is no longer supported and might no be working following the release of `scikit-learn` v1.2. In this PR, we update the system tests to use the `auto_trainer` function (also from the functions marketplace - https://github.com/mlrun/functions/blob/master/auto_trainer/auto_trainer.py) instead of the `sklearn_classifier`.

2023-01-01 11:07 UTC, guy1992l approved these changes

2023-01-02 21:22 UTC, AlonMaor14 commented
please change here https://github.com/mlrun/mlrun/blob/development/tests/system/projects/test_project.py#L89 as well

2023-01-03 07:57 UTC, guy1992l commented
> please change here https://github.com/mlrun/mlrun/blob/development/tests/system/projects/test_project.py#L89 as well

Its not affecting the test you've mentioned, we saw it. Anyway Eyal will do so.

2023-01-03 12:31 UTC, AlonMaor14 commented
Please check `tests/system/demos/sklearn/test_sklearn.py` as `sklearn_classifier` is being used there as well.
Also, if this function is now obsolete maybe we want to go over our docstrings because it's being mentioned many times as an example.
For example in `import_function`
```
def import_function(url="", secrets=None, db="", project=None, new_name=None):
    """Create function object from DB or local/remote YAML file

    Functions can be imported from function repositories (mlrun Function Hub (formerly Marketplace) or local db),
    or be read from a remote URL (http(s), s3, git, v3io, ..) containing the function YAML

    special URLs::

        function hub: hub://{name}[:{tag}]
        local mlrun db:       db://{project-name}/{name}[:{tag}]

    examples::

        function = mlrun.import_function("hub://sklearn_classifier")
        function = mlrun.import_function("./func.yaml")
        function = mlrun.import_function("https://raw.githubusercontent.com/org/repo/func.yaml")
```

2023-01-04 10:07 UTC, AlonMaor14 approved these changes
LGTM
@guy1992l @Tankilevitch please review so we can merge this (needed for a lot of system tests
@Eyal-Danieli can you please also update https://github.com/mlrun/project-demo - it needs to have the same changes and it is also used in many system tests

2023-01-04 10:07 UTC, AlonMaor14 commented on tests/system/projects/assets/kflow.py
> +    train = funcs["auto_trainer"].as_step(
Can you add a comment that the default handler is `train`? it wasn't clear to me at 1st sight

2023-01-04 15:53 UTC, guy1992l requested changes
tiny change

2023-01-04 15:53 UTC, guy1992l commented on mlrun/projects/operations.py
> +        run1 = run_function(function, params={"label_columns": LABELS}, inputs={"dataset": DATA_URI})
For the uri I would give a more random sample in the length of an actual uri.
```suggestion
        run1 = run_function(function, params={"label_columns":["target"]}, inputs={"dataset": "xxxxxxxxxx"})
```

2023-01-05 07:24 UTC, guy1992l requested changes
bla is not a cool doc string word :) also always try to make it readable to CE users as well (no v3io).

2023-01-05 07:24 UTC, guy1992l commented on mlrun/projects/operations.py
> +        DATA_PATH = "v3io:///bigdata/bla.parquet"
```suggestion
        DATA_PATH = "s3://bigdata/data.parquet"
```

2023-01-05 07:59 UTC, Eyal-Danieli commented on mlrun/projects/operations.py
> +        DATA_PATH = "v3io:///bigdata/bla.parquet"
Got it. Fixed.

2023-01-05 08:35 UTC, AlonMaor14 approved these changes

2023-01-05 08:38 UTC, merged