[Images] Build mlrun/models/models-gpu python 3.7 images
mlrun/mlrun pull request #2936
Opened 2023-01-17 10:28 UTC by AlonMaor14

2023-01-18 20:53 UTC, liranbg requested changes
minor

2023-01-18 20:53 UTC, liranbg commented on dockerfiles/mlrun-api/Dockerfile
> +FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}
```suggestion
FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}-slim
```

2023-01-18 20:53 UTC, liranbg commented on dockerfiles/mlrun/Dockerfile
> +FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}
```suggestion
FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}-slim
```

2023-01-18 20:53 UTC, liranbg commented on dockerfiles/test-system/Dockerfile
> +FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}
```suggestion
FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}-slim
```

2023-01-18 20:53 UTC, liranbg commented on dockerfiles/test/Dockerfile
> +FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}
```suggestion
FROM gcr.io/iguazio/python:${MLRUN_PYTHON_VERSION}-slim
```

2023-01-23 11:42 UTC, Tankilevitch requested changes
Looks good, minor comment for readability, also would be useful to add somewhere comment about the change we done to our base images that we removed the patch version and the version bump will be done in the docker registry.

2023-01-23 11:42 UTC, Tankilevitch commented on Makefile
> +MLRUN_ANACONDA_PYTHON_DISTRIBUTION = $(shell echo "$(MLRUN_PYTHON_VERSION)" | awk -F. '{print "-py"$$1$$2}')
let's add a comment for what is being outputes here

2023-01-23 12:39 UTC, AlonMaor14 commented on .github/workflows/build-workflow-matrix.json
> +    "include-suffix":""
add comment in the makefile because we can't write comments in json files

2023-01-24 07:40 UTC, Tankilevitch approved these changes

2023-01-24 07:40 UTC, merged