[Doc] Add documentation for FeatureSet.plot
mlrun/mlrun pull request #2956
Opened 2023-01-20 20:27 UTC by george0st

Add missing documentation for FeatureSet.plot

2023-01-22 13:50 UTC, assaf758 commented
Some minor comments.
Thanks for contributing!

2023-01-22 14:21 UTC, gtopper commented on mlrun/feature_store/feature_set.py
> +        :param with_targets:      show target in graph
Looks like the indentation is a bit off here.

2023-01-22 14:30 UTC, assaf758 requested changes

2023-01-23 21:07 UTC, assaf758 approved these changes

2023-01-23 21:07 UTC, merged