[Dask] Disable watch
mlrun/mlrun pull request #2989
Opened 2023-01-25 13:14 UTC by AlonMaor14

Since Dask runtime executes the handler / code locally, there is no point to watch the run logs as it blocks the client until completion either way.
https://jira.iguazeng.com/browse/ML-3296

2023-01-25 13:59 UTC, liranbg reviewed
See comments below

2023-01-25 16:42 UTC, AlonMaor14 commented on mlrun/runtimes/daskjob.py
> +        raise NotImplementedError(
I mistakenly decided to remove in 1.4.0 and later found the ticket in the description with the deprecation guidelines which says it should be removed now

2023-01-26 11:17 UTC, guy1992l approved these changes
Why the `NotImplemmentedError` is used instead of simply deleting the methods? Just to give the message?

If so, I would use the `with_scheduler/worker_requests` from these methods and print the user warning. In my eyes it seems healthier. Next version we may delete them all at once.

2023-01-26 11:17 UTC, guy1992l commented on mlrun/runtimes/base.py
> +                if watch and self.kind not in ["", "handler", "local", "dask"]:
Just a thought: I think there should be an enum for `RunTimeKinds`. There you can write methods like `def is_watchable(self) -> bool` and more to not have to edit lists in multiple locations of code. 

Also, what is `kind=""`?

2023-01-26 12:47 UTC, AlonMaor14 commented
> Why the `NotImplemmentedError` is used instead of simply deleting the methods? Just to give the message?
> 
> If so, I would use the `with_scheduler/worker_requests` from these methods and print the user warning. In my eyes it seems healthier. Next version we may delete them all at once.

Actually, it's to override the base class methods instead of removing them as it was described in the deprecation ticket https://jira.iguazeng.com/browse/ML-3104

2023-01-26 13:33 UTC, AlonMaor14 commented on mlrun/runtimes/base.py
> +                if watch and self.kind not in ["", "handler", "local", "dask"]:
@guy1992l I agree and this came to my mind as well
empty kind is a special case of `local` I don't exactly know when / why it happens but it's there

2023-01-26 13:41 UTC, AlonMaor14 commented on mlrun/runtimes/base.py
> +                if watch and self.kind not in ["", "handler", "local", "dask"]:
@guy1992l seems like this is already a thing `mlrun.runtimes.RuntimeKinds`

2023-01-26 14:17 UTC, Tankilevitch requested changes
very nice job, I would add test to make sure we really skip the watch and that job completes

2023-01-29 11:43 UTC, Tankilevitch requested changes

2023-01-29 11:43 UTC, Tankilevitch commented on tests/run/test_run.py
> +    func.spec.remote = False
why you need to set this?

2023-01-29 12:25 UTC, liranbg approved these changes

2023-01-29 13:04 UTC, AlonMaor14 commented on tests/run/test_run.py
> +    func.spec.remote = False
added comments

2023-01-29 13:07 UTC, Tankilevitch approved these changes
LGTM

2023-01-29 14:32 UTC, merged