[Projects] Stop logs for runs when deleting project
mlrun/mlrun pull request #3090
Opened 2023-02-14 14:54 UTC by TomerShor

A followup PR to #3082.

When deleting a project, call `stop_logs` for all of the project's runs before they and their resources(pods) are deleted.
This is done so the log collector won't get stuck trying to collect logs for non-existing runs.

Since the log collector client is async, this required moving all of the `delete_project` functions from sync to async.

2023-02-15 18:55 UTC, liranbg requested changes
this is a very dangerous change late in 1.3.0 development. lets discuss offline to see how to make such change with zero risk.

2023-02-15 18:55 UTC, liranbg commented on mlrun/api/crud/projects.py
> +    async def delete_project(
once you graduate a function to be async, you *must* follow all function inside calls to make sure all calls to IO are either async + await or sync and runs in threadpools. e.g. `verify_project_has_no_related_resources` must be run in threadpool.

2023-02-15 18:55 UTC, liranbg commented on mlrun/api/utils/projects/follower.py
> +    async def initialize(self):
see comment above

2023-02-15 18:55 UTC, liranbg commented on mlrun/api/utils/projects/follower.py
>          db_session = mlrun.api.db.session.create_session()
⚠️ blockig io in async

2023-02-19 14:05 UTC, closed without merging

2023-02-22 09:03 UTC, TomerShor commented
Implemented in https://github.com/mlrun/mlrun/pull/3145