[Functions] Mask sensitive data on `store_function`
mlrun/mlrun pull request #3096
Opened 2023-02-15 17:11 UTC by Tankilevitch

2023-02-19 15:00 UTC, theSaarco requested changes
Looks good in general. Have some comments and suggestions...

2023-02-19 16:48 UTC, alonmr approved these changes
LGTM. Left a question and a suggestion.

2023-02-19 16:48 UTC, alonmr commented on tests/integration/sdk_api/projects/test_project.py
> +                    function.to_dict(),
we should probably add a type hint for `function` in `store_function`

2023-02-19 16:48 UTC, alonmr commented on mlrun/runtimes/pod.py
> +                # valueFrom is a workaround for now, for some reason the envs aren't getting sanitized
sounds like s bug. shouldn't we resolve this instead of hiding it?

2023-02-20 12:36 UTC, alonmr approved these changes

2023-02-20 12:52 UTC, theSaarco approved these changes
👍

2023-02-20 13:05 UTC, merged