[Serving] Add logger prints
mlrun/mlrun pull request #3244
Opened 2023-03-09 14:13 UTC by guy1992l

Added logger prints to better understand in what phase of initialization a Nuclio v2 serving function get stuck when initialization fails.

2023-03-09 14:25 UTC, liranbg requested changes
Remove "..." that is not an interactive program 
Also, when logging with variables use
logger.debug_with("message", some="thing")

2023-03-09 14:57 UTC, liranbg requested changes
last one

2023-03-09 14:57 UTC, liranbg commented on mlrun/serving/server.py
> +    context.logger.info("Initializing states")
```suggestion
    context.logger.info_with("Initializing states", namespace= namespace)
```

2023-03-09 14:57 UTC, liranbg commented on mlrun/serving/server.py
>      serving_handler = server.init_object(namespace or get_caller_globals())
i would suggest to also dive into `init_states` `init_object` and see if logs can be applied to them as well 
(as long as they r executed once, it is ok)

2023-03-09 15:42 UTC, liranbg commented
> Remove "..." that is not an interactive program Also, when logging with variables use logger.debug_with("message", some="thing")

note to self, serving function logger does not support log_with. its logger is mlrun logger. thus no need to do `x_with` but simply provide the variable. `logger.debug("message", some="thing")` @guy1992l fyi

2023-03-09 17:14 UTC, liranbg approved these changes

2023-03-09 17:15 UTC, merged

2023-03-12 21:51 UTC, assaf758 commented on mlrun/serving/states.py
> +            context.logger.info("Initializing step", step=step.name)
This new log completely spams the log!
please remove @guy1992l @liranbg