[Artifact] Enforce the update of artifacts with conflicting keys
mlrun/mlrun pull request #3295
Opened 2023-03-16 14:11 UTC by yaelgen

Adding a fix for: https://jira.iguazeng.com/browse/ML-3604

While the body key is a non-empty string, we will not allow POSTing  that includes "key" with bodies that contain a different "key".

2023-03-22 10:14 UTC, alonmr requested changes
please see `mlrun.api.db.sqldb.db.SQLDB._process_artifact_dict_to_store`
there is a comparison between key and db_key. We should move it there so that both verifications will be in the same place.
Also, don't forget about legacy artifacts which are deprecated but should still be supported until 1.5.0.

2023-03-22 10:14 UTC, alonmr commented on mlrun/api/crud/artifacts.py
> +            data_key = data["metadata"].get("key")
```suggestion
        data_key = data.get("metadata", {}).get("key")
```

2023-04-02 16:13 UTC, alonmr reviewed
Looks good! A couple of minor comments and I'm missing a test for legacy artifacts.

2023-04-02 16:13 UTC, alonmr commented on tests/api/api/test_artifacts.py
> +    assert resp.status_code == HTTPStatus.BAD_REQUEST.value
assert the error message as well

2023-04-02 16:13 UTC, alonmr commented on mlrun/api/db/sqldb/db.py
> +                f"Artifact with conflicting key name - {data_key} while request key : {key}."
I suggest having a similar error message for both errors (here and in line 542)
and please add the keys to the message similarly above (and with the legacy artifact)
```suggestion
                f"Conflict between requested key ({key}) and key in artifact metadata ({data_key})"
```

2023-04-25 06:34 UTC, liranbg requested changes

2023-04-25 06:34 UTC, liranbg commented on mlrun/api/db/sqldb/db.py
> +                f"Conflict between requested key ({key}) and key in artifact metadata ({db_key})"
line 542, 550, and 577 have the same exact failure message. why? can you refine the messages so backtracking of why/where it failed would be more clear to developer? that way, would be easier to understand from tests what have failed.

2023-05-08 14:22 UTC, closed without merging