[Runtime] Split server-client `run` skeleton
mlrun/mlrun pull request #3342
Opened 2023-03-26 17:10 UTC by alonmr

2023-03-28 19:25 UTC, liranbg requested changes

2023-03-28 19:25 UTC, liranbg commented on mlrun/api/launcher/server.py
> +class ServerSideLauncher(AbstractLauncher):
```suggestion
class Launcher(AbstractLauncher):
```

It is enough here as enyway it "lives" under "api" which essentially means it is a server-side launcher.

2023-03-28 19:25 UTC, liranbg commented on mlrun/api/launcher/server.py
> +        super().__init__(**kwargs)
not needed

2023-03-28 19:25 UTC, liranbg commented on mlrun/api/launcher/server.py
> +class ServerSideLauncher(AbstractLauncher):
also, I think you can move it alltogether under `mlrun/api/launcher.py`

2023-03-28 19:25 UTC, liranbg commented on mlrun/launcher/abstract.py
> +        pass
separate them

2023-03-28 19:25 UTC, liranbg commented on mlrun/launcher/abstract.py
> +        pass
`build_required`

2023-03-28 19:25 UTC, liranbg commented on mlrun/launcher/client/local.py
> +class ClientLocalLauncher(AbstractLauncher):
Id expect the `mlrun/launcher` source tree to be like:

mlrun/launcher/factory.py
mlrun/aluncher/base.py
mlrun/aluncher/local.py
mlrun/aluncher/remote.py

class, w.r.t class names

base.py
`_BaseLauncher()`

local.py
`LocalLauncher()`

2023-03-28 19:25 UTC, liranbg commented on mlrun/launcher/client/local.py
> +class ClientLocalLauncher(AbstractLauncher):
by that, you will remove many files/dirs that are overwhelming for now. also, keep the functions stubs to minimal, let them grow upon need / tasks

2023-04-04 09:10 UTC, liranbg approved these changes
very minor. lgtm! 🏅

2023-04-04 09:10 UTC, liranbg commented on mlrun/launcher/factory.py
> +    def create_launcher(local) -> _BaseLauncher:
type hint on local?

2023-04-04 09:12 UTC, Tankilevitch reviewed
General wonder, seems a bit weird that common code will import code from the API, although the api launcher is backend side maybe it should be in the common code.
@liranbg @quaark @theSaarco wdyt?

2023-04-04 09:20 UTC, quaark commented
> General wonder, seems a bit weird that common code will import code from the API, although the api launcher is backend side maybe it should be in the common code.
> @liranbg @quaark @theSaarco wdyt?

That's what we spoke about in the meeting. Yes this is a bit strange, but it's ok and we'll still be able to package the client and server separately as the import happens within the `if` statement.
I don't think `ServerSideLauncher` should sit in common, as that is exactly the server side implementation which should sit with the rest of the server code.

2023-04-04 11:09 UTC, quaark approved these changes

2023-04-04 11:14 UTC, merged