[Schemas] Move API Pydantic schemas to common
mlrun/mlrun pull request #3461
Opened 2023-04-30 16:18 UTC by TomerShor

Our pydantic schemas are used all over the code base, but are located under `mlrun.api.schemas`.
This caused almost every module to import from the `api` module, although not related to the api at all.

In this PR, I moved all schemas to `mlrun/common`.
For backwards compatibility, `mlrun.api.schemas` can still be used. However - it is now raising a deprecation warning and return the actual schema from `mlrun.common.schemas` (see `mlrun/api/schemas/__init__.py`).

A part of the server-client separation.

Implements https://jira.iguazeng.com/browse/ML-3774

2023-05-03 13:06 UTC, Tankilevitch requested changes
Pt1 of review

2023-05-03 13:06 UTC, Tankilevitch commented on mlrun/api/api/utils.py
> +from mlrun.common.schemas import SecretProviderName, SecurityContextEnrichmentModes
same

2023-05-03 13:06 UTC, Tankilevitch commented on mlrun/api/crud/artifacts.py
> +from mlrun.common.schemas.artifact import ArtifactsFormat
same

2023-05-03 13:06 UTC, Tankilevitch commented on mlrun/api/crud/marketplace.py
> +from mlrun.common.schemas.marketplace import (
same

2023-05-03 13:06 UTC, Tankilevitch commented on mlrun/api/crud/model_monitoring/grafana.py
> +from mlrun.common.schemas import (
same

2023-05-03 13:06 UTC, Tankilevitch commented on mlrun/api/db/base.py
> +import mlrun.common.schemas
<3

2023-05-03 13:06 UTC, Tankilevitch commented on mlrun/utils/helpers.py
> +        )
I suggest passing a version as well so user will have an idea when we are planning to deprecate

2023-05-07 08:15 UTC, liranbg approved these changes

2023-05-07 08:36 UTC, Tankilevitch approved these changes
Looks good

2023-05-07 08:36 UTC, Tankilevitch approved these changes
Looks good

2023-05-07 08:41 UTC, merged