[Tests] Increase dockerized tests timeout
mlrun/mlrun pull request #3472
Opened 2023-05-03 13:37 UTC by yaelgen

fails locally, increasing the timeout solves the problem.

2023-05-03 20:27 UTC, Tankilevitch requested changes
I am not sure this should be the solution as it can cause us miss possible decreases in performance.

Possible solution I see is resolving the timeout based on the system we are running on, if for example we run in github actions leave it as 30 and if not running in actions set to 90, as on personal computer the timeout can be differ due to poor network connection etc.

2023-05-04 07:35 UTC, Tankilevitch commented
> I am not sure this should be the solution as it can cause us miss possible decreases in performance.
> 
> Possible solution I see is resolving the timeout based on the system we are running on, if for example we run in github actions leave it as 30 and if not running in actions set to 90, as on personal computer the timeout can be differ due to poor network connection etc.

Discussed with @quaark offline, decided that it is ok to increase the timeout so developers on apple silicon won't fail on the integration tests as now it takes longer to load due to the qume emulator, and in addition @yaelgen will add a test that actually tests the desired timeout (30 sec) like we had before

2023-05-04 07:37 UTC, quaark commented
> > I am not sure this should be the solution as it can cause us miss possible decreases in performance.
> > Possible solution I see is resolving the timeout based on the system we are running on, if for example we run in github actions leave it as 30 and if not running in actions set to 90, as on personal computer the timeout can be differ due to poor network connection etc.
> 
> Discussed with @quaark offline, decided that it is ok to increase the timeout so developers on apple silicon won't fail on the integration tests as now it takes longer to load due to the qume emulator, and in addition @yaelgen will add a test that actually tests the desired timeout (30 sec) like we had before

I'll clarify, @yaelgen please add a test that will only test the api boot up speed (30 seconds). Add a comment explaining it'll probably fail on an Apple Silicon Mac, but passes on native x86 architecture.

2023-05-15 19:24 UTC, liranbg requested changes

2023-05-15 19:24 UTC, liranbg commented on tests/rundb/test_httpdb.py
> +    " which will most likely fail this test due to the qume emulator,"
```suggestion
    " which will most likely fail this test due to the qemu being slow,"
```

2023-05-15 19:24 UTC, liranbg commented on tests/rundb/test_httpdb.py
> +    " but should pass on native x86 architecture",
```suggestion
    " but should pass on native architecture",
```

2023-05-15 19:24 UTC, liranbg commented on tests/rundb/test_httpdb.py
> +    for i in range(run_times):
```suggestion
    for _ in range(run_times):
```

2023-05-15 19:24 UTC, liranbg commented on tests/rundb/test_httpdb.py
> +    assert sum(runs) / run_times <= expected_time
```suggestion
    avg_run_time = sum(runs) / run_times
    assert avg_run_time <= expected_time, "Seems like a performance hit on creating api server"
```

2023-05-15 19:24 UTC, liranbg commented on tests/rundb/test_httpdb.py
> +    assert sum(runs) / run_times <= expected_time
better explain _why_ the assertion failed - throw a bone to whoever fails on it
in addition, better save the magic calculations on a side variable to give it a name of what we calculate

2023-05-15 21:49 UTC, merged