[Projects] Fix BC for GET requests of non-normalized function names
mlrun/mlrun pull request #3568
Opened 2023-05-16 13:38 UTC by yaelgen

follow up for: https://github.com/mlrun/mlrun/pull/3287
In this previous PR we added a normalization to a function name before saving it, and notify the user of the change.

We realized that in case our users ignored/missed the warning when setting the function, and then attempted to access (import or update) it later,  they would be unable to do so using the old name, and would not know why their function was not found.

As a result, as long as we do not block requests with non-normalized names, we will normalize GET requests as well.
In this fix we handle this case by adding fall-back to get_function:
Normalize the requested name and attempt to retrieve it from the database. if no response is received, we will check to see if the original name contained underscores,  if so, we will repeat the retrieval and return the result (if exists).

The backwards compatibility behavior here is:
In circumstances when the user has an old function with non-normalized name already saved in the database, he will be able to retrieve it.
If he makes an update request, we will create a new updated function, with a normalized name. Now if he attempts to retrieve it using the old name, we will first normalize the name in the request for him, and return the updated function.

2023-05-16 14:17 UTC, Tankilevitch requested changes
Nice Job! very concise and straight to the point @yaelgen

2023-05-16 14:17 UTC, Tankilevitch commented on tests/api/api/test_projects.py
> +def test_get_project_function_when_using_not_normalize_name(
Looking at the logic you are testing I think this need to be under the `tests_functions` and on the DB layer, as you are not actually testing any "API" logic over here but mainly that the `db` layer is able to return a function with an underscore.

2023-05-16 14:17 UTC, Tankilevitch commented on tests/projects/test_project.py
> +    )
```suggestion
    project = mlrun.projects.MlrunProject(
        "project"
    )
```

2023-05-16 14:17 UTC, Tankilevitch commented on tests/projects/test_project.py
> +
😍

2023-05-21 10:52 UTC, liranbg requested changes
Well done! few things
1. Add type hint / param explanation for public functions you encounter and change, will help future developers
2. Public functions before private functions, try to push down the internal implementation of get function after all public class apis
3. It is legitimate to log that you function was not found, trying to find function without normalizing its name

2023-05-23 06:40 UTC, liranbg reviewed
last one

2023-05-23 06:40 UTC, liranbg commented on mlrun/api/db/sqldb/db.py
> +                )
Id change the debug verbose to warning
and change the log to use kwargs, so once we have json formatter, those kwargs would be indexed well

```python
logger.warning("Failed to get underscore-named function, trying without normalization", function_name=name)
```

2023-05-23 11:43 UTC, liranbg approved these changes

2023-05-23 13:39 UTC, Tankilevitch approved these changes
LGTM

2023-05-23 13:39 UTC, Tankilevitch commented on mlrun/projects/project.py
> +        In sync mode, we first preform a sync of the function_objects from the function_definitions,
```suggestion
        In sync mode, we first perform a sync of the function_objects from the function_definitions,
```

2023-05-23 17:39 UTC, merged