[Notifications] Fix missed notifications in notifications pusher
mlrun/mlrun pull request #3607
Opened 2023-05-21 17:34 UTC by yaelgen

Adding a fix to `_push_terminal_run_notifications`. 
`_last_notification_push_time` was calculated after querying and pushing all runs, therefore a run could have been missed. Taking the time now before running the query.

This change lead to some scheduler tests taking longer and fail. 
We computed a margin of `0.5` seconds for these tests, which was already quite insufficient (`0.4` is not enough), and increased it to `0.8` in this PR.
It looks like adding even one CPU-consuming code line along the flow will cause a delay in the run time. 

This margin will only work temporarily, and we don't want this actions to influence the run time. In the future, we should consider separating this server code, but for now, we should discuss a better solution (maybe make scheduler tests not run the periodic run monitor + add a test for the real flow expected time).

2023-05-21 20:04 UTC, Tankilevitch commented
seems like we are experiencing the import loops again

2023-05-22 18:35 UTC, liranbg requested changes

2023-05-22 18:35 UTC, liranbg commented on tests/api/utils/test_scheduler.py
> +schedule_end_time_margin = 0.7
I think what needs to be done here is to run notifications monitoring under a feature flag
and when running scheduler tests, simply disable it

2023-05-22 18:35 UTC, liranbg commented on mlrun/api/main.py
> -    import mlrun.api.api.utils
welp, that didnt work

revert change or tackle in other PR

2023-05-24 07:07 UTC, merged