[API] Use APIRouter prefix where possible
mlrun/mlrun pull request #3615
Opened 2023-05-22 12:45 UTC by yanburman

2023-05-22 13:20 UTC, liranbg requested changes

2023-05-22 13:20 UTC, liranbg commented on mlrun/api/api/endpoints/tags.py
> +router = fastapi.APIRouter(prefix="/projects/{project}/tags/{tag}")
Tags currently support detail endpoints but that is not true for the future as each endpoint (tags in this case) need to support list endpoints as well

tl;dr - when you use router prefix, do it for the restful bucket not containing its ID too

2023-05-23 06:35 UTC, liranbg approved these changes

2023-05-29 10:52 UTC, Tankilevitch approved these changes

2023-05-29 10:52 UTC, merged