[API] Fix get pipelines return code in case of nonexistent project
mlrun/mlrun pull request #3625
Opened 2023-05-23 12:48 UTC by yanburman

https://jira.iguazeng.com/browse/ML-1267

2023-05-23 13:52 UTC, Tankilevitch requested changes
Looking at the logic that is being "catched" it seems quite weird that if we don't find that pipeline under the requested project we return `MLRunInvalidArgumentError` which returns 400, while I would expect to get 404 which is the mlrun error - `MLRunNotFoundError`.

please adjust it as well

2023-05-23 13:52 UTC, Tankilevitch requested changes
Looking at the logic that is being "catched" it seems quite weird that if we don't find that pipeline under the requested project we return `MLRunInvalidArgumentError` which returns 400, while I would expect to get 404 which is the mlrun error - `MLRunNotFoundError`.

please adjust it as well

2023-05-25 19:37 UTC, liranbg approved these changes

2023-05-29 10:52 UTC, Tankilevitch approved these changes

2023-05-29 10:52 UTC, merged