[Model Monitoring] Fix event error message in monitoring stream graph
mlrun/mlrun pull request #3639
Opened 2023-05-24 10:27 UTC by Eyal-Danieli

A fix for https://jira.iguazeng.com/browse/ML-3791.

When there is an error in the event dictionary, the monitoring stream graph returns `None` instead of raising an exception with the related error information. As a result, instead of getting the correct error information, the monitoring stream pod raise an error from `Storey` that can't handle a `None` event object. 

In this PR we fix this issue and raise the correct error event description instead of returning a `None` object. Therefore, storey will push the right error message to the error stream and the monitoring stream will log the right error message as expected.

2023-05-24 12:39 UTC, assaf758 requested changes

2023-05-24 12:39 UTC, assaf758 commented on mlrun/model_monitoring/stream_processing_fs.py
> +        self.handle_errors(endpoint_id, event)
in my opinion the function name / flow is confusing - we call function handle_errors() even when there are no errors..
suggest to move ```if "error" in event:``` outside of the function

2023-05-28 10:29 UTC, gtopper approved these changes
Other than that small suggestion it LGTM

2023-05-28 10:29 UTC, gtopper commented on mlrun/model_monitoring/stream_processing_fs.py
> +            raise mlrun.errors.MLRunInvalidArgumentError(f"{event['error']}")
I guess this is a bit better
```suggestion
        error = event.get("error")
        if error:
            self.error_count[endpoint_id] += 1
            raise mlrun.errors.MLRunInvalidArgumentError(str(error))
```

2023-05-29 07:36 UTC, liranbg approved these changes

2023-05-29 07:36 UTC, merged