[Project] Optionally add function tag to key of project function dicts
mlrun/mlrun pull request #3739
Opened 2023-06-13 08:04 UTC by alonmr

https://jira.iguazeng.com/browse/ML-3992
In order to enable function versioning in the project's function dicts we will add the function tag if it was provided and the function name was not.

- [ ] Add tag option to `get_function`
- [ ] Add unit tests

2023-06-13 19:28 UTC, liranbg approved these changes

2023-06-13 19:56 UTC, Tankilevitch requested changes

2023-06-13 19:56 UTC, Tankilevitch commented on tests/projects/test_project.py
> +    assert func.metadata.tag == tag
seems redundant

2023-06-13 19:56 UTC, Tankilevitch commented on tests/projects/test_project.py
> +
```suggestion

    func = project.get_function(f"{my_func.metadata.name}:{tag}", tag=tag)
    assert func.metadata.tag == tag

```

2023-06-14 08:42 UTC, Tankilevitch approved these changes

2023-06-14 08:42 UTC, merged