Update dev_utilities.py
mlrun/mlrun pull request #3780
Opened 2023-06-19 13:11 UTC by eliyahu77

2023-06-19 18:19 UTC, liranbg commented on automation/system_test/dev_utilities.py
> +        pass
no need to pass if you print the exception.
also, why the `# !!!`?

2023-06-20 12:54 UTC, Tankilevitch requested changes

2023-06-20 12:54 UTC, Tankilevitch commented on automation/system_test/dev_utilities.py
> +        print(e)
```suggestion
        print(e)
```

2023-06-20 12:54 UTC, Tankilevitch commented on automation/system_test/dev_utilities.py
> +        pass
```suggestion
    except Exception as e:
        print(e)
```

2023-06-20 12:54 UTC, Tankilevitch commented on automation/system_test/dev_utilities.py
> +    except Exception as e:  # !!!
```suggestion
    except Exception as e:
```

2023-06-20 13:37 UTC, merged