[Package] Replace `mpi4py` with host name check
mlrun/mlrun pull request #4104
Opened 2023-08-15 13:43 UTC by guy1992l

* Replace `mpi4py` with host name check - get the rank out of the host name template (`<name>-worker-<rank>`)
* Add a TODO and fix tiny doc typo in `NonePackager`

2023-08-15 16:05 UTC, liranbg requested changes

2023-08-16 07:13 UTC, alonmr commented on mlrun/package/context_handler.py
> +            rank = int(self._context.labels["host"].rsplit("-", 1)[1])
@guy1992l see tests.system.runtimes.test_mpijob.TestMpiJobRuntime.test_run_state_completion for reference

2023-08-16 09:27 UTC, guy1992l commented on mlrun/package/context_handler.py
> +            rank = int(self._context.labels["host"].rsplit("-", 1)[1])
done

2023-08-16 11:40 UTC, alonmr approved these changes

2023-08-16 14:56 UTC, liranbg approved these changes

2023-08-16 14:57 UTC, merged