[Packager] English edits
mlrun/mlrun pull request #4120
Opened 2023-08-17 19:48 UTC by jillnogold

2023-09-18 09:23 UTC, guy1992l commented
Problem here is you have changed error messages that are being validated for being raised in tests. You need to change them in the failed test or roll back the error edits.

2023-09-19 06:03 UTC, guy1992l requested changes

2023-09-19 14:36 UTC, jillnogold commented on mlrun/package/packagers/default_packager.py
> +      configurations are sent by the user and are mandatory. If unspecified, they get a default value.
@guy1992l How does the user set a default value? If we want to say it should have a default - think we should explain that.

2023-09-28 12:05 UTC, jillnogold commented on docs/api/mlrun.package.rst
> +original code. The packagers are defined in the function code of a project.
reverted to your wording

2023-10-01 12:10 UTC, guy1992l approved these changes
:)

2023-10-02 08:43 UTC, merged