[Runtimes] support databricks abort.
mlrun/mlrun pull request #4165
Opened 2023-08-28 14:17 UTC by tomerm-iguazio

1) Support for aborting Databricks jobs is available.
 When aborting a Databricks job, utilize a Kubernetes hook named `pre_stop` before deleting the runtime's pod. By using this hook, mlrun can execute a script capable of canceling the job within the Databricks environment.
2) User-defined Databricks run names are now supported:
`{"task_parameters": {"databricks_run_name": databricks_run_name}}`
3) An abort test has been added.

2023-08-29 12:01 UTC, gtopper requested changes

2023-08-29 12:01 UTC, gtopper commented on mlrun/runtimes/databricks_job/databricks_wrapper.py
> +    is_finished=False,
I don't see any benefit in the default values.
```suggestion
    cluster_id: typing.Optional[str],
    is_finished: bool,
```

2023-08-29 12:12 UTC, tomerm-iguazio commented on tests/system/runtimes/test_databricks.py
> +\n
It is just a task that is going to be aborted later, so the sleep length should not be a problem. However, a short sleep period will cause the job to end before we abort it.

2023-08-29 12:23 UTC, tomerm-iguazio commented on mlrun/runtimes/databricks_job/databricks_wrapper.py
> +        credentials["DATABRICKS_CLUSTER_ID"] = token
nice catch!

2023-08-30 10:28 UTC, gtopper commented on tests/system/runtimes/test_databricks.py
> +        run_thread.start()
```suggestion
        function.run(project=self.project_name, params=params, watch=False)
```

2023-08-30 10:58 UTC, gtopper commented on tests/system/runtimes/test_databricks.py
> +        time.sleep(5)
Pretty sure you need to sleep before `get_run` for the sleep to have any effect (other than slowing the test down).

2023-08-30 10:58 UTC, gtopper commented on tests/system/runtimes/test_databricks.py
> +        #  in order to clean up any active runs:
```suggestion
        #  in order to clean up any active runs
```

2023-08-30 11:02 UTC, gtopper commented on tests/system/runtimes/test_databricks.py
> +        # wait for databricks to run the function.
```suggestion
        # wait for databricks to run the function
```

2023-08-30 11:03 UTC, gtopper commented on tests/system/runtimes/test_databricks.py
> +        databricks_run_name = f"databricks_abort_test_{test_run_uid}"
```suggestion
        databricks_run_name = f"databricks_abort_test_{uuid.uuid4()}"
```

2023-08-30 11:05 UTC, gtopper commented on tests/system/runtimes/test_databricks.py
> +        print("start aborting")
Better use `self._logger`.

2023-08-30 11:06 UTC, gtopper commented on mlrun/runtimes/databricks_job/databricks_cancel_task.py
> +    #  use for flat structure only.
```suggestion
    # use for flat yaml only
```

2023-08-31 11:21 UTC, gtopper approved these changes
✅

2023-08-31 12:03 UTC, merged