[Notification] Add secret_params to notification
mlrun/mlrun pull request #4170
Opened 2023-08-29 11:29 UTC by yaelgen

follow up to: https://jira.iguazeng.com/browse/ML-4498

This PR tackles a space-saving issue with project secrets. Currently, they're all stored in a single secret, which doesn't get cleaned up.
To fix this, we're separating "params" into "params" and "secret_params." This simple change should significantly reduce the space problem.
In the PR linked above, we set the secret key as the hash of the secret_params themselves. That way if the same secret is used multiple times, it won't take up more space than a single instance.

2023-08-29 13:10 UTC, quaark requested changes
Looks good!
Very minor, also revert everything in CustomNotificationPusher

2023-08-29 13:10 UTC, quaark commented on mlrun/__main__.py
> -            notification_type=notification_type, params=notification_params
not needed here, revert to params :)

2023-08-29 18:05 UTC, liranbg reviewed
Does it take care of notification secrets from
Older mlrun version (eg 1.4.1)?

2023-08-30 06:02 UTC, quaark commented
> Does it take care of notification secrets from
> Older mlrun version (eg 1.4.1)?

yes it does because of how the migrations are done in the db, all the previous params will be secret params

2023-08-30 06:04 UTC, quaark approved these changes
🚀 great stuff

2023-08-30 06:04 UTC, merged