[Project] Delete Project Background Task
mlrun/mlrun pull request #4784
Opened 2023-12-21 08:21 UTC by quaark

2023-12-25 12:10 UTC, TomerShor requested changes
Nice one mate,
Only a couple of minor suggestions.

Also - can it would be nice to see a new test that validates the background tasks or a system test of sorts.

2023-12-25 12:10 UTC, TomerShor commented on server/api/api/endpoints/healthz_v2.py
Is this actually needed?
Can't we reuse the v1 `healthz` as the v2_router's `healthz` as well?

2023-12-25 12:10 UTC, TomerShor commented on server/api/api/endpoints/projects_v2.py
> +    return False
duplicate function from `projects.py`, can be moved to a helper function.

2023-12-25 13:54 UTC, TomerShor approved these changes
LGTM 👍

2023-12-25 14:06 UTC, alonmr reviewed
Looks great! Minor comments

2023-12-26 07:06 UTC, quaark commented
> Nice one mate, Only a couple of minor suggestions.
> 
> Also - can it would be nice to see a new test that validates the background tasks or a system test of sorts.

It's a bit of an issue/already covered. The MLRun leader flow is covered in regular integration tests that already test deleting the project. For the full flow only a system test will do. However, all the system tests are already creating and deleting projects. So I wonder if it's worth making them longer for something they already do. The test itself will literally be:
```
def test_delete_project():
    pass
```

2023-12-26 08:01 UTC, alonmr approved these changes
Looks good! Couple of minor suggestions

2023-12-27 15:58 UTC, merged