[Datastore] Allow passing GCS credentials as a json string
mlrun/mlrun pull request #4874
Opened 2024-01-04 12:58 UTC by alxtkr77

https://jira.iguazeng.com/browse/ML-5451

2024-01-07 14:44 UTC, tomerm-iguazio commented
![image](https://github.com/mlrun/mlrun/assets/125267619/7a8b27c9-8ffc-44f8-8d72-77e221402496)
![image](https://github.com/mlrun/mlrun/assets/125267619/07d25131-49fe-488d-b757-9fa378dfc6fb)

Every test failed in mlrun/tests/integration/google_cloud_storage/test_google_cloud_storage.py.
3 tests failed in mlrun/tests/system/datastore/test_google_cloud_storage.py.
**Please open a PR only after checking all relevant tests** (these integration and system tests are not running in the ci):

`mlrun/tests/system/datastore/test_google_cloud_storage.py`
`mlrun/tests/integration/google_cloud_storage/test_google_cloud_storage.py`

2024-01-07 14:55 UTC, tomerm-iguazio requested changes

2024-01-07 14:55 UTC, tomerm-iguazio commented on mlrun/datastore/google_cloud_storage.py
> +            and google_credentials != gcp_credentials
In `google_credentials` you Will get a path to a credential file.
They should never be the same!

If you want, you can read the file and compare its data.

2024-01-07 14:55 UTC, tomerm-iguazio commented on tests/system/datastore/test_google_cloud_storage.py
> +        try:
why try and except is needed?

2024-01-07 14:55 UTC, tomerm-iguazio commented on mlrun/datastore/google_cloud_storage.py
> +                credentials = json.loads(credentials)
why do you need to use try and except?

2024-01-07 14:55 UTC, tomerm-iguazio commented on mlrun/datastore/google_cloud_storage.py
> +                credentials = json.loads(credentials)
json.loads will not work on a path to json file, as GOOGLE_APPLICATION_CREDENTIALS.

2024-01-09 11:44 UTC, assaf758 approved these changes

2024-01-09 11:44 UTC, merged