[Doc] Update serving example
mlrun/mlrun pull request #5047
Opened 2024-02-01 13:19 UTC by jillnogold

[ML-5563](https://jira.iguazeng.com/browse/ML-5563)

2024-02-01 15:07 UTC, alonmr requested changes
minor

2024-02-01 15:07 UTC, alonmr commented on docs/runtimes/serving-function.md
> +project_name_base = 'serving-test'
```suggestion
project_name_base = 'serving-project'
```

2024-02-11 13:32 UTC, jillnogold commented on docs/runtimes/serving-function.md
> +project_name_base = 'serving-test'
updated

2024-02-19 11:40 UTC, alonmr approved these changes

2024-02-19 11:40 UTC, merged