[Model Monitoring] Fix path filtering according to nuclio changes
mlrun/mlrun pull request #5058
Opened 2024-02-04 14:33 UTC by davesh0812

Works also on previous nuclio versions.
[ML-5659](https://jira.iguazeng.com/browse/ML-5659)

2024-02-04 15:54 UTC, Eyal-Danieli approved these changes
cool cool cool
We just need to make sure that it works in CE (prometheus) as expected. Anyway, it seems correct.

2024-02-04 16:41 UTC, assaf758 requested changes

2024-02-04 16:41 UTC, assaf758 commented on mlrun/model_monitoring/stream_processing.py
>          # through the next steps of the stream graph
```suggestion
        # Step 2 - Filter out events with '-' in the path basename from going forward
        # through the next steps of the stream graph
```

2024-02-05 08:14 UTC, assaf758 approved these changes

2024-02-05 09:00 UTC, merged