[Serving] Enable sending model inputs as dict by new operation infer_dict or predict_dict
mlrun/mlrun pull request #5107
Opened 2024-02-11 14:43 UTC by davesh0812

https://jira.iguazeng.com/browse/ML-5705

2024-02-12 14:02 UTC, theSaarco requested changes
I'm a bit concerned about our expanding the API which is supposed to be standard, but we're doing it anyway by introducing new types of inputs. So, at a minimum this should be documented.
Also, you have a small bug there - see comments.

2024-02-12 14:02 UTC, theSaarco commented on tests/serving/test_serving.py
> +    resp_list = server.test("/v2/models/m1/infer", testdata_iris)
Test also `/v2/models/m1/predict` - this will expose the issue I commented on earlier.

2024-02-15 11:05 UTC, davesh0812 commented on mlrun/serving/v2_serving.py
> +            or op == "predict_dict"
@theSaarco  You want me to open a documentation ticket for that?

2024-02-19 06:41 UTC, theSaarco commented on mlrun/serving/v2_serving.py
> +            or op == "predict_dict"
Yes, I think we need to see where this makes sense to document - it should be part of the docstring, for sure, but maybe we want to introduce using this into one of the tutorials that demonstrate serving as well.

2024-02-19 06:42 UTC, theSaarco approved these changes
LGTM.

2024-02-19 15:52 UTC, merged