[Docs] Re-arrange data store content
mlrun/mlrun pull request #5226
Opened 2024-03-03 12:32 UTC by jillnogold

2024-03-04 08:02 UTC, assaf758 requested changes

2024-03-04 08:02 UTC, assaf758 commented on docs/store/datastore.md
> +- [HDFS data store profile](#hdfs-data-store-profile)
these "TOC" titles should point to the datastore, not the datastore profile

2024-03-04 08:02 UTC, assaf758 commented on docs/store/datastore.md
>  ```{admonition} Notes
in my opinion a note about lack of support in specific use-case should be at then end of chapter, when datastore profile is already explained

2024-03-04 08:02 UTC, assaf758 commented on docs/store/datastore.md
>  ### GCS data store profile
Here you are describing the profile before the parameters.
I suggest you keep it consistent - first the parameters, then the profile.

2024-03-04 08:02 UTC, assaf758 commented on docs/store/datastore.md
> +## HDFS data store profile
section ## HDFS data store
Here you can mention that we don't support HDFS with env-vars, only with datastore profile
subsection ### HDFS datastore profile

2024-03-04 08:02 UTC, assaf758 commented on docs/store/datastore.md
> +## Azure
Azure datastore

2024-03-13 09:02 UTC, jillnogold commented on docs/store/datastore.md
>  ```{admonition} Notes
my theory was that you don't want to read all this if it's not relevant for you. , but moving it to the bottom

2024-03-18 10:40 UTC, assaf758 approved these changes

2024-03-18 10:40 UTC, merged