[Model Monitoring] Test and Fix for Model-monitoring data-path: support LLM/deep-learning models
mlrun/mlrun pull request #5289
Opened 2024-03-14 14:22 UTC by davesh0812

Implements and test https://iguazio.atlassian.net/browse/ML-5459

One important change : no more saving prediction as a vec or as a dict to the parquet (no one used it), only each port to separated column according to the model schema (if there is no schema so stream pod generated it).

2024-03-17 11:50 UTC, gtopper commented on tests/system/model_monitoring/assets/models.py
> +# Copyright 2023 Iguazio
```suggestion
# Copyright 2024 Iguazio
```

2024-03-19 07:01 UTC, assaf758 requested changes
Some minor comment inline.
Still need to check if it helps for BC to save empty list/dict

2024-03-19 07:01 UTC, assaf758 commented on tests/system/model_monitoring/test_app.py
> +    image: typing.Optional[str] = "docker.io/davesh0812/mlrun:1.7.0"
Please remove

2024-03-19 07:01 UTC, assaf758 commented on mlrun/model_monitoring/controller.py
> -            labels = endpoint[mm_constants.EventFieldType.LABEL_NAMES]
why is this removed?

2024-03-20 08:40 UTC, davesh0812 commented on mlrun/model_monitoring/controller.py
> -            labels = endpoint[mm_constants.EventFieldType.LABEL_NAMES]
@assaf758  currently we are not using it, and if we wish to update the fs schema we need to it from the stream pod

2024-03-20 10:37 UTC, assaf758 approved these changes

2024-03-20 10:37 UTC, merged