[Tensorflow] Fix import
mlrun/mlrun pull request #5375
Opened 2024-04-03 12:56 UTC by gtopper

tensorflow 2.16.1 breaks `tensorflow.keras.callbacks`.

`tensorflow.python.keras.callbacks` works with tensorflow 2.16.1 as well as with previous versions.

2024-04-04 07:34 UTC, guy1992l requested changes
Good catch Gal. For backward compatibility please check tf.__version__ and import accordingly

2024-04-04 07:39 UTC, gtopper commented
@guy1992l, from my testing, `import tensorflow.python.keras.callbacks` works with older versions as well.

2024-04-07 10:21 UTC, guy1992l requested changes
I've read more and since TensorFlow 2.6, Keras got separated and being released as a pip package (like its used to be before TensorFlow 1.12 I think). So, to get access to the `Callback`, please do as I suggested in the comments.

See here a tutorial from tensorflow: https://www.tensorflow.org/guide/keras/writing_your_own_callbacks?hl=en

IMO, we can say we only support TF 2.6 and on to skip the version checking... But lets keep it for now I guess (I'll ask Nir if we have anyone who use TF with lower versions).

2024-04-07 10:21 UTC, guy1992l commented on mlrun/frameworks/tf_keras/callbacks/logging_callback.py
> +from tensorflow.python.keras.callbacks import Callback
```suggestion
if tf.__version__.split(".")[1] < 6:
    tensorflow.keras.callbacks import Callback
else:
    from keras.callbacks import Callback
```

2024-04-07 10:21 UTC, guy1992l commented on mlrun/frameworks/tf_keras/mlrun_interface.py
>  )
```suggestion
if tf.__version__.split(".")[1] < 6:
    from tensorflow.keras.callbacks import (
        BaseLogger,
        Callback,
        CSVLogger,
        ModelCheckpoint,
        ProgbarLogger,
        TensorBoard,
    )
else:
    from keras.callbacks import (
        BaseLogger,
        Callback,
        CSVLogger,
        ModelCheckpoint,
        ProgbarLogger,
        TensorBoard,
    )
```

2024-04-08 06:57 UTC, guy1992l approved these changes

2024-04-08 08:11 UTC, assaf758 approved these changes

2024-04-08 08:11 UTC, merged