[Docs] Add an example how to use `log_artifact` method
mlrun/mlrun pull request #5411
Opened 2024-04-10 08:16 UTC by GiladShapira94

2024-04-11 07:35 UTC, jillnogold approved these changes

2024-04-14 09:46 UTC, jillnogold approved these changes

2024-04-14 11:00 UTC, alonmr requested changes
Minor typos and conventions

2024-04-14 11:00 UTC, alonmr commented on docs/store/log-artifacts.md
> +You can apply this nethod to the project object or the context object when logging an artifact in runtime, for example a job.
```suggestion
You can apply this method to the project object or the context object when logging an artifact in runtime, for example a job.
```

2024-04-14 11:00 UTC, alonmr commented on docs/store/log-artifacts.md
> +                     format="html")
```suggestion
project.log_artifact("plotly-artifact",
                     body=fig.to_html(), # Convert object for logging an html file
                     format="html")
```

2024-04-14 11:00 UTC, alonmr commented on docs/store/log-artifacts.md
> +context.log_artifact(plotly_artifact)
To be consistent with the other comments
```suggestion
# Use mlrun to convert the python object
plotly_artifact = mlrun.artifacts.PlotlyArtifact(figure=fig, key="sin_x") 
# Log the artifact
context.log_artifact(plotly_artifact) 
```

2024-04-15 08:14 UTC, jillnogold approved these changes

2024-04-15 09:37 UTC, jillnogold commented on docs/store/log-artifacts.md
> +
**Log with local path**
```python
    with open("file.txt","w") as f:
        f.write("abc is 123")

    project.log_artifact(
        "file-example",
        local_path="file.txt",
        labels={"Test": "label-test"},
    )

**Log with body**
```python
    project.log_artifact(
        "some-data",
        body=b"abc is 123",
        format="txt",
        labels={"Test": "label-test"},
    )
```

2024-04-15 10:42 UTC, jillnogold approved these changes

2024-04-15 11:50 UTC, alonmr approved these changes

2024-04-15 11:51 UTC, merged