[Projects] Adding `allow_cross_project` flag for creating project from template
mlrun/mlrun pull request #5453
Opened 2024-04-21 14:23 UTC by roei3000b

https://iguazio.atlassian.net/issues/ML-5741

2024-04-21 14:58 UTC, jillnogold commented on docs/projects/project-setup.md
> +### Loading project from template
### Loading a project from a template
You can load a project from a template only if one of the following conditions is met:
- Set the `allow_cross_project` flag = True and change the name of the project.
- Change the name in the yaml file or delete it.
- Change the context dir .

2024-04-28 06:53 UTC, liranbg requested changes
some wordings and consistency

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +            project = _load_project_file(from_template, name, secrets, True)
```suggestion
            project = _load_project_file(from_template, name, secrets, allow_cross_project True)
```
consistency

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +    :param allow_cross_project: if True, allow loading a project with a different name than the provided name
```suggestion
    :param allow_cross_project: if True, override the loaded project name. This flag ensures awareness of loading an existing project yaml as a baseline for a new project with a different name
```

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +            logger.warn(f"The yaml file was generated for {name_from_struct} project")
```suggestion
            logger.warn("Project name is different than specified on its project yaml. Overriding.", existing_name=name_from_struct, overriding_name=name)
```

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +                "1. Use the allow_cross_project flag.\n"
```suggestion
                "1. Set the `allow_cross_project=True` when loading the project.\n"
```

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +                "2. The yaml file needs to be deleted or edited to change the name in it.\n"
```suggestion
                f"2. Delete the existing project yaml, or ensure its name is equal to {name}"\n
```

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +                "3. The context dir needs to be changed."
```suggestion
                "3. Use different project context dir."
```

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +                context, self.metadata.name, self.spec.subpath, False
```suggestion
                context, self.metadata.name, self.spec.subpath, allow_cross_project=False
```

2024-04-28 06:53 UTC, liranbg commented on mlrun/projects/project.py
> +                self.spec.origin_url, self.metadata.name, self._secrets, False
```suggestion
                self.spec.origin_url, self.metadata.name, self._secrets, allow_cross_project=False
```

2024-04-30 18:02 UTC, liranbg approved these changes

2024-04-30 18:02 UTC, merged