[Nuclio] Refactor API Gateway class to inherit from `ModelObj`
mlrun/mlrun pull request #5464
Opened 2024-04-25 13:52 UTC by TomerShor

Align API Gateway object with the rest of the MLRun objects by inheriting from `ModelObj` class.
This organizes the API Gateway properties under `metadata` and `spec`, as well as  allows using the known methods such as `to_dict` / `to_yaml`.

2024-04-25 14:01 UTC, liranbg approved these changes

2024-04-25 14:08 UTC, rokatyy commented on mlrun/runtimes/nuclio/api_gateway.py
>          )
Let's move validate to spec

2024-04-25 14:19 UTC, TomerShor commented on mlrun/runtimes/nuclio/api_gateway.py
>          )
makes sense 👍

2024-04-25 14:53 UTC, alonmr requested changes

2024-04-25 14:53 UTC, alonmr commented on mlrun/runtimes/nuclio/api_gateway.py
> +        self.spec = APIGatewaySpec(
see the following example on how to define meta and spec. constructor should only have meta and spec params
```
    @property
    def metadata(self) -> ProjectMetadata:
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        self._metadata = self._verify_dict(metadata, "metadata", ProjectMetadata)

    @property
    def spec(self) -> ProjectSpec:
        return self._spec

    @spec.setter
    def spec(self, spec):
        self._spec = self._verify_dict(spec, "spec", ProjectSpec)
```

2024-04-25 14:53 UTC, alonmr commented on mlrun/runtimes/nuclio/api_gateway.py
> +        ],
I feel like this can be simpler. Can't union accept more than 2 options?

2024-04-29 06:01 UTC, liranbg approved these changes

2024-04-29 06:26 UTC, merged