[ProjectSummaries] Make `_calculate_pipelines_counters` use pagination
mlrun/mlrun pull request #5496
Opened 2024-05-02 12:13 UTC by roei3000b

Fix bug in function `_calculate_pipelines_counters` - it ignored the return value of `page_token` from `_list_pipelines` and because of that if there were some pages, we only return the statistics for the first page.
Fixing it by using pagination in `list_pipelines` function.

https://iguazio.atlassian.net/browse/ML-6121

2024-05-02 12:25 UTC, rokatyy approved these changes
LGTM! Added just one minor suggestion

2024-05-02 12:25 UTC, rokatyy commented on server/api/crud/projects.py
> +
Could be simplified a bit
```suggestion
            next_page_token = ""
            while True:
                (
                    _,
                    next_page_token,
                    pipelines,
                ) = await fastapi.concurrency.run_in_threadpool(
                    server.api.db.session.run_function_with_new_db_session,
                    self._list_pipelines,
                    page_token=next_page_token,
                )
                for pipeline in pipelines:
                    if (
                        pipeline["status"]
                        not in mlrun.run.RunStatuses.stable_statuses()
                    ):
                        project_to_running_pipelines_count[pipeline["project"]] += 1
               if not next_page_token:
                   break     

```

2024-05-02 12:34 UTC, liranbg requested changes
Missing a unit test

2024-05-03 04:08 UTC, liranbg approved these changes

2024-05-03 04:08 UTC, merged