[API Gateways] Support access key authentication
mlrun/mlrun pull request #5509
Opened 2024-05-05 10:32 UTC by TomerShor

Add support for access key authentication mode, that uses the Cookie header with Iguazio access key for authentication.

Implements https://iguazio.atlassian.net/browse/ML-6359

2024-05-05 12:02 UTC, liranbg requested changes
condition that on minimum iguazio version (where you have the fix to support control planes

2024-05-05 13:25 UTC, liranbg approved these changes

2024-05-05 14:42 UTC, alonmr requested changes
Looks good! A few small comments

2024-05-05 14:42 UTC, alonmr commented on mlrun/platforms/iguazio.py
> +                f"Iguazio {mlconf.nuclio_version}."
you are using `mlconf.nuclio_version` in the message

2024-05-05 14:42 UTC, alonmr commented on mlrun/runtimes/nuclio/api_gateway.py
> +from ...platforms.iguazio import min_iguazio_versions
dont add relative imports

2024-05-05 14:42 UTC, alonmr commented on mlrun/platforms/iguazio.py
> +def validate_iguazio_version_compatibility(*min_versions):
I feel like this is code duplication maybe we can merge it with `validate_nuclio_version_compatibility`

2024-05-05 14:42 UTC, alonmr commented on tests/platforms/test_iguazio.py
> +        print(f"Testing case: {case}")
change print to log and use pytest parameterize because it will continue for the other cases if one of them fails

2024-05-06 11:08 UTC, alonmr approved these changes

2024-05-06 12:47 UTC, merged