[Alerts] Modify to have list of ids per alert
mlrun/mlrun pull request #5511
Opened 2024-05-05 13:01 UTC by yanburman

2024-05-07 15:40 UTC, theSaarco requested changes
Some pretty minor comments, but let's make sure our naming and terminology is consistent.

2024-05-07 15:40 UTC, theSaarco commented on mlrun/alerts/alert.py
> +    def with_entity(self, entity: alert_constants.EventEntities):
```suggestion
    def with_entities(self, entities: alert_constants.EventEntities):
```

If we're renaming, let's adjust the sdk accordingly.

2024-05-07 15:40 UTC, theSaarco commented on server/api/crud/alerts.py
> +            if id in alert_entity.ids:
Why double iteration? I assume an event will only have a single entity ID (that's why I also let the field still be called `entity` in the Event class rather than `entities`) - you're even validating this in the CRUD.

2024-05-08 12:48 UTC, theSaarco approved these changes
LGTM

2024-05-09 07:21 UTC, quaark requested changes
I don't really understand this PR, and I feel it is adding instability to the code without adding any functionality at all. 
Why would we change the id/entity to a list of ids/entities which we validate to always be a length of 1, and any time we access it we always access `ids[0]`? 
Let's either actually extend the functionality to work with lists or stay with single entity, this "preparation" adds complexity and instability in my honest opinion. (And I'll also add that the PR should explain the rationality of the change as well)

@theSaarco as you approved this PR, maybe you could comment here as well?

2024-05-09 11:48 UTC, theSaarco commented
This is to prepare for future stages where we will as support for multiple entities in a single alert. We want to be ready without having to modify the data structures and go with BC changes. 
The sdk currently allows adding a single entity, until such time where we remove the limitation.

2024-05-09 12:10 UTC, quaark approved these changes
Spoke with @theSaarco and @yanburman offline and understood the magnitude of implementing multiple entity support is out of scope at the current release, so we will keep the preparation for the next release.
@yanburman please add some info on the plans of the multiple entity support in the PR description.

2024-05-12 11:35 UTC, merged