[FrontendSpec] Adding TTLCache to `try_get_grafana_service_url` function
mlrun/mlrun pull request #5543
Opened 2024-05-09 14:47 UTC by roei3000b

Adding TTLCache to `try_get_grafana_service_url` function.

https://iguazio.atlassian.net/browse/ML-5874

2024-05-13 09:24 UTC, liranbg requested changes

2024-05-13 09:24 UTC, liranbg commented on server/api/utils/clients/iguazio.py
> +    @cachetools.cached(cache=cachetools.TTLCache(maxsize=1, ttl=120))
I assume LRU right? then if we you 100k different sessions - how many records would you save? 
I think the approach you have taken is a plaster. the reason it needs to be cached is because its callee resolves the jupyter url twice which results in 2 api calls to igz.
so the idea is to make a single call to igz and use its results once.

2024-05-15 08:38 UTC, roei3000b commented on server/api/utils/clients/iguazio.py
> +    @cachetools.cached(cache=cachetools.TTLCache(maxsize=1, ttl=120))
As we discussed, because we want to cache the result per **session**, and because the ttl is only 2 minutes it's ok with our users scale.

2024-05-15 09:11 UTC, liranbg approved these changes

2024-05-15 13:14 UTC, merged