[API] Check the artifact kind while attempting to remove artifact data
mlrun/mlrun pull request #5545
Opened 2024-05-12 09:16 UTC by moranbental

Data artifacts that are `ModelArtifact`, `DirArtifact`, or `DatasetArtifact` must not be removed because we do not yet support the deletion of artifacts that contain multiple files.

If the `deletion strategy` is `"data-force"` and one of these artifact kinds is attempted to be deleted, the error `MLRunNotImplementServerError` will be raised.

https://iguazio.atlassian.net/browse/ML-6432

2024-05-12 09:28 UTC, theSaarco commented on server/api/crud/artifacts.py
> +                )
Please add a comment explaining why we do this now, and a `TODO` to remove once we add support.

2024-05-12 09:41 UTC, theSaarco approved these changes
LGTM.

2024-05-13 06:06 UTC, alonmr requested changes
Looks good! Small touch ups

2024-05-13 06:06 UTC, alonmr commented on mlrun/errors.py
> +class MLRunNotImplementServerError(MLRunHTTPStatusError):
```suggestion
class MLRunNotImplementedServerError(MLRunHTTPStatusError):
```

2024-05-13 06:06 UTC, alonmr commented on server/api/crud/artifacts.py
> +                    ) from exc
Just raise the exception you got, what if you get 404 or 400, you wouldn't want to wrap it with internal error

2024-05-13 07:33 UTC, alonmr approved these changes

2024-05-13 09:19 UTC, merged