[Alerts] Add support for summary message
mlrun/mlrun pull request #5590
Opened 2024-05-19 13:10 UTC by yanburman

2024-05-19 13:48 UTC, theSaarco requested changes
Looks good, but what about unit tests?
Also, there's another location in `alert.py` where you're using the `$project` and `$entity` notation - should be modified as well.

2024-05-19 14:18 UTC, theSaarco reviewed
ok, but I thought to add a test to verify that the place-holders are indeed being replaced when formatting events. 
You can add a simple unit test that calls `format_alert_summary` directly for now, but we should have a test that the functionality is working as expected. Of course, this should also be verified with more complex tests later.

2024-05-21 06:46 UTC, theSaarco approved these changes
Sababa

2024-05-21 07:06 UTC, quaark approved these changes

2024-05-21 07:06 UTC, merged