[Model Monitoring] Reuse monitoring function images
mlrun/mlrun pull request #5607
Opened 2024-05-21 15:21 UTC by TomerShor

*Background:*
The model monitoring infra deploys multiple nuclio functions per project. These functions are basically identical in every project. 
Up until now, each model monitoring enablement through MLRun triggered multiple simultaneous nuclio image builds, since MLRun used `code` as entry type, and provided a base-image, which resulted in nuclio building the images, and a major load on large-scale systems, as the kaniko build pods took a lot of resources - causing starvation to other kubernetes resources.

*Solution:*
To improve this, we will reuse the built images for each of the monitoring functions across projects.
We are utilizing Nuclio's ability to deploy a function from an existing image, and skipping the build stage.

**Image Manifest:**
For that, we create an image manifest caching mechanism.
When each of the model monitoring functions is first built, we save the resulted image in the cache, with keys as a combination of mlrun version, nuclio version, and the base image.
Specifically, this is the image manifest format:
```json
{
    <mlrun+nuclio_versions_hash>: {
        <function_name>: {
            <base_image>: <built_nuclio_image>,
        }
    }
}
```

The manifest is saved as a json file on the mounted `db` folder, so it will persist restarts of the api pod.

***Using the manifest:***
When model monitoring is enabled in a different project, we look for the existing image in the manifest according to the version+base_image combination:
- If it exists - we deploy the functions with this image.
- If an image does not exist for this combination - the function will be deployed with a newly built image

Note: a new query param `force_build` was added to allow not reusing the images.

***Updating the manifest:***
In Nuclio, the built image is populated on the function status only once the function is deployed successfully and ready.
Since these functions can take time to be deployed, we do not want to block the `enable_model_monitoring` endpoint by waiting for them to be ready.
So - we create a **background task** to wait for the functions to be ready, and only then update the image manifest with the created images.
If the images for key combination already exist - we do not update them as there as the images have already been reused.

Resolves https://iguazio.atlassian.net/browse/ML-6408

2024-05-22 08:26 UTC, quaark requested changes
I feel like using a file here is a bad practice and will cause issues in the future. In my opinion we should create a new SQL table here and save the cache persistently there.
Otherwise looks good!

2024-05-22 08:26 UTC, quaark commented on server/api/crud/model_monitoring/deployment.py
> +    def _update_image_manifest(
I'd like this method to work parallel. Writing to the manifest file parallel is a bad practice. But you can wait for the nuclio deployments in parallel. Wait for all the statuses to arrive and then write to the file. (Unless we make these rows in a DB table in which case everything can be parallel)

2024-05-22 12:46 UTC, liranbg requested changes

2024-05-22 12:46 UTC, liranbg commented on server/api/crud/model_monitoring/deployment.py
> +        self._read_image_manifest()
this does not survive restarts. why not sql table?

2024-05-22 12:46 UTC, liranbg commented on server/api/crud/model_monitoring/deployment.py
> +        # TODO: remove this once the api will support deploying functions from an existing image directly
maybe elaborate here / add jira reference to what needs to be done here

2024-05-22 12:46 UTC, liranbg commented on server/api/crud/model_monitoring/deployment.py
> +                json.dump(self._image_manifest, f)
note that this is not threadsafe

2024-05-23 11:00 UTC, gtopper commented on server/api/crud/model_monitoring/deployment.py
> +                "The stream function is not deployed yet when the user will run `enable_model_monitoring` "
```suggestion
                "The stream function is not deployed yet. When the user runs `enable_model_monitoring` "
```

2024-09-01 13:17 UTC, closed without merging