[Function] Optimise an error when function deletion is failed
mlrun/mlrun pull request #5646
Opened 2024-05-28 15:31 UTC by rokatyy

Currently, the error string can be too long, so I have removed the additional string about failure for every Nuclio function. There will still be a message indicating that the deletion failed, including the MLRun function name.

So, instead of this 

```
Failed to delete function func-nuclio. Errors: Failed to delete nuclio function run-nuclio-hello-world-func-nuclio: 412, message='Precondition Failed', url=URL('http://nuclio-dashboard.default-tenant.svc.cluster.local:8070/api/functions/'): : Function is "
```

we will have:

```
Failed to delete function func-nuclio. Errors: Function is used by api gateways"
```

Jira - https://iguazio.atlassian.net/browse/ML-6552

2024-05-28 19:53 UTC, TomerShor requested changes

2024-05-28 19:53 UTC, TomerShor commented on server/api/api/utils.py
> +                    failed_requests.append(error_message)
See [my comment on JIRA](https://iguazio.atlassian.net/browse/ML-6552?focusedCommentId=151269), and try to extract the relevant info from the exception

2024-05-30 06:28 UTC, TomerShor commented
@rokatyy can you updated the description with the new error after your latest change? I'd like to see how it look

2024-05-30 08:46 UTC, rokatyy commented
@TomerShor updated

2024-05-30 13:29 UTC, TomerShor approved these changes

2024-06-02 07:16 UTC, merged