[API] Support Minimal Artifact Format
mlrun/mlrun pull request #5691
Opened 2024-06-03 07:20 UTC by quaark

https://iguazio.atlassian.net/browse/ML-6659

*waiting for minimal format spec to add to the formatter

2024-06-10 13:25 UTC, TomerShor requested changes
Nice! Minor comments

2024-06-10 13:25 UTC, TomerShor commented on mlrun/db/httpdb.py
> +            "format": mlrun.common.formatters.ArtifactFormat.full,
Is this still true?
Can't we just pass `_format`?

2024-06-10 13:25 UTC, TomerShor commented on mlrun/db/httpdb.py
> +            "format": mlrun.common.formatters.ArtifactFormat.full,
Same here?
```suggestion
            "format": format_,
```

2024-06-17 10:55 UTC, mavdryk commented on mlrun/common/formatters/artifact.py
> +                    "spec.metrics",
please don't forget to add `spec.target_path`

2024-06-18 07:44 UTC, TomerShor approved these changes

2024-06-19 10:27 UTC, merged