[Run] Set the default run kind to local
mlrun/mlrun pull request #5709
Opened 2024-06-04 08:33 UTC by moranbental

When a user creates a context in local (rather than a run) from `get_or_create_context` , it creates a local run that cannot be aborted or deleted. The issue is that you can't delete the run because it doesn't have a kind.
For that, I changed the default run kind to local.

https://iguazio.atlassian.net/browse/ML-4636

2024-06-04 18:31 UTC, liranbg reviewed
very well, minor comment

2024-06-04 18:31 UTC, liranbg commented on mlrun/execution.py
> +        run_kind = self.labels.get(mlrun_constants.MLRunInternalLabels.kind, "")
update the comment above it, explaining the reasoning to allow changing run state for local

2024-06-05 07:57 UTC, liranbg requested changes

2024-06-05 07:57 UTC, liranbg commented on tests/test_execution.py
> +    assert run["status"]["state"] == "completed", "run status was updated in db"
read the comment. the assertion is wrong now.

2024-06-05 09:18 UTC, alonmr reviewed
Looks nice! Minor touch up requests

2024-06-05 09:18 UTC, alonmr commented on mlrun/execution.py
> +        # If the run is local, we can change the state to completed, so it doesn't stay in running mode forever.
can you make the comment a bit more coherent? something like
> Completion of runs is decided by the API runs monitoring as there may be multiple executions for a single run (e.g. mpi). For kinds that are not monitored by the API (local) we allow changing the state.

2024-06-05 09:18 UTC, alonmr commented on tests/integration/sdk_api/run/test_run.py
> +
```suggestion
        # remove internal labels
        assert mlrun_constants.MLRunInternalLabels.host in runs[0]["metadata"]["labels"]
        del runs[0]["metadata"]["labels"][mlrun_constants.MLRunInternalLabels.host]
        assert mlrun_constants.MLRunInternalLabels.kind in runs[0]["metadata"]["labels"]
        del runs[0]["metadata"]["labels"][mlrun_constants.MLRunInternalLabels.kind]

```

2024-06-05 09:18 UTC, alonmr commented on tests/run/assets/simple.py
> +def func():
can make the handler name a bit more meaningful
```suggestion
def get_ctx_kind_label():
```

2024-06-05 10:16 UTC, merged