[Docs] Add links for both api gateways schema
mlrun/mlrun pull request #5714
Opened 2024-06-04 10:41 UTC by rokatyy

2024-06-04 11:17 UTC, alonmr commented on docs/api/mlrun.api_gateways.rst
shouldn't it be `mlrun.runtimes/mlrun.runtimes.api_gateways.rst` ?

2024-06-04 11:19 UTC, rokatyy commented on docs/api/mlrun.api_gateways.rst
@alonmr why would it? the docs structure has nothing to do with code structure, api_gateway is not a sub-entity of runtime, so I'd add it as a separate entity in MLRun docs.

2024-06-04 12:55 UTC, moranbental requested changes

2024-06-04 13:07 UTC, moranbental commented on docs/api/mlrun.api_gateways.rst
I think you should create new folder of `docs/api/mlrun.runtimes` and move the `docs/api/mlrun.runtimes.rst` inside this folder and rename it to `index.rst` and then create new folder `docs\api\mlrun.runtimes\nuclio` with `index.rst` inside that will calls to `docs\api\mlrun.runtimes\nuclio\api_gatway.rst`
so then in the future we can auto module all the docstrings

2024-06-04 13:21 UTC, rokatyy commented on docs/api/mlrun.api_gateways.rst
@moranbental could you please explain how it will change the behaviour of docs generation? APIGateway-related code is in api_gateway.py file, so it will be always generated properly and be updated. Also, as I said above api_gateway is not a runtime, so it would not be correct from UX perspective to place it under the mlrun.runtimes.

2024-06-05 18:35 UTC, moranbental approved these changes

2024-06-05 18:35 UTC, moranbental commented on docs/api/mlrun.api_gateways.rst
If it is not related to runtime, why is `api_gateway.py` in the runtime module in the first place?
When you import APIGateway you do this - `import mlrun.runtimes.nuclio.api_gateway.APIGateway`. So, I believe it should be in the same directory, but under /docs, because each is a module.  Then it will be easier to auto-modulate other classes/functions in the other module.

2024-06-06 13:05 UTC, TomerShor commented on docs/api/mlrun.runtimes/index.rst
Is this still needed following https://github.com/mlrun/mlrun/pull/5725?

2024-06-06 13:05 UTC, TomerShor commented on docs/api/mlrun.runtimes/mlrun.runtimes.rst
same question?

2024-06-06 13:59 UTC, rokatyy commented on docs/api/mlrun.runtimes/index.rst
it will be reverted https://github.com/mlrun/mlrun/pull/5730

2024-06-19 07:24 UTC, TomerShor approved these changes

2024-06-19 07:28 UTC, merged