[Functions] Remove the explicit status removal
mlrun/mlrun pull request #5849
Opened 2024-06-26 11:00 UTC by rokatyy

2024-06-26 15:12 UTC, TomerShor requested changes
Minor

2024-06-26 15:12 UTC, TomerShor commented on server/api/db/sqldb/db.py
> +                # TODO: remove explicit cleaning
Comment what you wrote in the Jira, about multiple functions in the UI

2024-06-27 06:44 UTC, TomerShor commented on server/api/db/sqldb/db.py
> +                #  will need to understand how to display functions in UI), because if we simply delete this string,
```suggestion
                #  will need to understand how to display functions in UI, because if we do not remove the status here,
```

2024-06-27 08:02 UTC, TomerShor approved these changes

2024-06-27 09:53 UTC, liranbg approved these changes

2024-06-27 09:53 UTC, merged