[Docs] Add application runtime
mlrun/mlrun pull request #6036
Opened 2024-07-23 09:12 UTC by jillnogold

2024-07-23 09:32 UTC, alonmr commented on docs/runtimes/application.ipynb
> +{
<ol><li>I would remove the <code>(a web application)</code> part from the top or change it to <code>(e.g. a web application)</code></li><li> pull at run-time is not supported yet.</li><li>API gateway can be disabled to allow free access without authentication</li></ol><p>		&gt;The deployment ensures an API Gateway</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlrun/mlrun/pull/6036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2024-07-23 09:32 UTC, alonmr commented on docs/runtimes/application.ipynb
> +{
<p>set_internal_app_port was change to set_internal_application_port</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlrun/mlrun/pull/6036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2024-07-23 09:32 UTC, alonmr commented on docs/runtimes/application.ipynb
> +{
<p>This feature was cancelled</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlrun/mlrun/pull/6036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2024-07-23 09:32 UTC, alonmr commented on docs/runtimes/application.ipynb
> +{
<p>need to change a few things the example is not up to date</p><p>add the following lines:</p><p>application.set_internal_application_port(&lt;add-your-port&gt;)</p><p>application.spec.command = &lt;add-command-string&gt;</p><p>application.spec.args = &lt;add-command-args-list-of-strings&gt;</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlrun/mlrun/pull/6036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2024-07-23 20:28 UTC, TomerShor commented on docs/runtimes/application.ipynb
> +{
<blockquote>The application runtime deploys a user container image (for example, a web application), a port, and a command to run the HTTP server. </blockquote><p>This sentence is not accurate, as it doesn't "deploy a port and a command", it deploys a container image that is exposed on a specific port.</p><p> </p><blockquote>or use a pre-built image</blockquote><p>As Alon said, this is not supported.</p><p> </p><blockquote>you can disable it to allow free access without authentication. </blockquote><p>The authentication can be disabled, not the API Gateway. Maybe something like:</p><p>"... is in front of the application and can provide different authentication methods, or none"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlrun/mlrun/pull/6036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2024-07-24 06:18 UTC, jillnogold commented
@alonmr @TomerShor - Thanks!

2024-08-11 11:17 UTC, TomerShor requested changes

2024-08-11 11:17 UTC, TomerShor commented on docs/concepts/nuclio-real-time-functions.ipynb
> +    "```python\n",
i'm not sure the `python` magic is working in `ipynb` files, it's mostly for `md` files.

2024-08-11 11:17 UTC, TomerShor commented on docs/runtimes/application.ipynb
> +    "The application runtime deploys a container container image (for example, a web application) that is exposed on a specific port, and a command to run the HTTP server. The runtime is based on top
```suggestion
    "The application runtime deploys a container image (for example, a web application) that is exposed on a specific port, and a command to run the HTTP server. The runtime is based on top of Nuclio, and adds the application as a side-car to a Nuclio function pod while the actual function is a reverse proxy to that application. 
    You can set an existing image to run in the application , or let the application runtime build the side-car image for you, by specifying the source code, and pulling at build-time. 
    An API Gateway, by default, is in front of the application and can provide different authentication methods, or none.\n",
```

2024-08-12 12:20 UTC, TomerShor approved these changes

2024-08-13 19:04 UTC, merged