[Alerts] Change default reset policy to auto
mlrun/mlrun pull request #6040
Opened 2024-07-23 11:44 UTC by yanburman

2024-07-30 09:19 UTC, alonmr commented on tests/system/alerts/test_alerts.py
> +            reset_policy=alert_objects.ResetPolicy.MANUAL,
please add a comment why in system tests you use manual

2024-08-04 09:39 UTC, Yacouby commented on tests/system/alerts/test_alerts.py
> +            reset_policy=alert_objects.ResetPolicy.MANUAL,
it is not a must to use manual here, this line can be deleted

2024-08-04 09:43 UTC, Yacouby requested changes

2024-08-04 09:43 UTC, Yacouby commented on tests/system/alerts/test_alerts.py
> +            reset_policy=alert_objects.ResetPolicy.MANUAL,
```suggestion
```

2024-08-08 07:07 UTC, alonmr approved these changes

2024-08-08 07:07 UTC, merged