[Datastore] Snowflake upper case handling
mlrun/mlrun pull request #6057
Opened 2024-07-28 15:22 UTC by tomerm-iguazio

Due to snowflake transformation to uppercase columns:

1) Raise error in ingestion if using SnowflakeSource with lower case timestamp_key/ entity/ label_column + test.
2) Add a test for ingestion with parquet source with lower case columns and snowflake target.

[ML-7223](https://iguazio.atlassian.net/browse/ML-7223)

2024-07-30 13:02 UTC, theSaarco submitted a review, later dismissed
Overall looks good - I have some small comments around docs/messages.

2024-07-30 13:02 UTC, theSaarco commented on docs/feature-store/sources-targets.md
> +```
Maybe be a bit more informative here? Would be great to add an example code where a `SnowflakeSource` class is used as source and an entity name (or timestamp field etc.) is provided with lowercase letter, explaining that this code will fail? Similar to the example we have in [SQL source](https://docs.mlrun.org/en/latest/feature-store/sources-targets.html#sql-source).

2024-07-30 13:02 UTC, theSaarco commented on mlrun/datastore/sources.py
> +    @classmethod
Why a `classmethod`? Usually this is done to generate new instances of the given class, here you don't really care what `cls` is. Looks like this should be a static method.

2024-07-30 13:02 UTC, theSaarco commented on mlrun/datastore/sources.py
> +                    f"Snowflake supports timestamp_key as uppercase only during ingestion."
```suggestion
                    f"Snowflake source only supports uppercase timestamp_key during ingestion."
```

2024-07-30 13:02 UTC, theSaarco commented on mlrun/datastore/sources.py
> +            "Snowflake supports entity as uppercase only during ingestion. entity:"
```suggestion
            "Snowflake source only supports uppercase entity names during ingestion. Entity name:"
```

2024-07-30 13:02 UTC, theSaarco commented on mlrun/datastore/sources.py
> +                    f"Snowflake supports label_column as uppercase only during ingestion. label_column: {label_column}"
```suggestion
                    f"Snowflake source only supports uppercase label_column during ingestion. label_column: {label_column}"
```

2024-07-30 14:38 UTC, tomerm-iguazio commented on mlrun/datastore/sources.py
> +    @classmethod
switch to different method from utils...

2024-08-01 14:54 UTC, assaf758 requested changes

2024-08-01 14:54 UTC, assaf758 commented on docs/feature-store/sources-targets.md
> +os.environ["SNOWFLAKE_PASSWORD"] = "*****"
Better give a description and  working example and then add a note about uppercase.

2024-08-01 14:54 UTC, assaf758 commented on tests/system/feature_store/test_spark_snowflake.py
> +    def test_feature_set_wrong_letters_case(self):
since the fix is generic (not specific to source) no need for specific test for snowflake.

2024-08-04 10:44 UTC, assaf758 requested changes

2024-08-04 10:44 UTC, assaf758 commented on docs/feature-store/sources-targets.md
> +```
```suggestion
# Notice that by default, Snowflake converts to uppercase name of columns ingested to it.
# The feature-set entity, timestamp_key and label_coumnt must have similar case to the source, othewise the ingest will faile with MLRunInvalidArgumentError exception
```

2024-08-04 15:30 UTC, assaf758 approved these changes

2024-08-04 15:32 UTC, merged