[DOCS] Update Model Serving docs
mlrun/mlrun pull request #6112
Opened 2024-08-06 09:27 UTC by davesh0812

https://iguazio.atlassian.net/browse/ML-5770

2024-08-06 10:35 UTC, assaf758 requested changes
Good stuff.
Some comments on the md

2024-08-06 10:35 UTC, assaf758 commented on docs/serving/model-api.md
> +Let me know if there's anything else you'd like to add!
Remove this line :-)

2024-08-06 10:35 UTC, assaf758 commented on docs/serving/model-api.md
> +For convenience, users can also pass a list of lists to enable batch processing.
Remove this line (redundant) as mentioned in "Batch input"

2024-08-06 10:35 UTC, assaf758 commented on docs/serving/model-api.md
> +     - Example: `[feature1, feature2, feature3, ...]`
Any restrictions on the type of the individual feature?

2024-08-06 10:35 UTC, assaf758 commented on docs/serving/model-api.md
> +- This API is particularly helpful when the user does not remember the order of the features.
Better start with description of what it is before following with the benefits

2024-08-06 11:20 UTC, davesh0812 commented on docs/serving/model-api.md
> +     - Example: `[feature1, feature2, feature3, ...]`
the type have o be serializable - add this sentence in 2 places.

2024-08-06 13:04 UTC, jillnogold commented on docs/serving/model-api.md
> +This API support only batch mode.
This API only supports batch mode.

2024-08-06 13:06 UTC, jillnogold commented on docs/tutorials/03-model-serving.ipynb
> +    "Deploy the serving function and use `invoke` to test it with the provided `sample` by 2 API's `infer` & `infer_dict`."
"Deploy the serving function and use `invoke` to test it with the provided `sample` by using 2 API's `infer` & `infer_dict`."

2024-08-06 17:52 UTC, jillnogold commented on docs/serving/model-api.md
> +  1. **Single Data Point Input:**
- **Single Data Point Input:**

2024-08-06 17:52 UTC, jillnogold commented on docs/serving/model-api.md
> +  2. **Batch Input:**
- **Batch Input:**

2024-08-06 17:53 UTC, jillnogold commented on docs/serving/model-api.md
> +- **id**: Unique Id of the request, if not provided a random value is provided.
- **id**: Unique ID of the request. If not provided a random value is used.

2024-08-06 17:54 UTC, jillnogold commented on docs/serving/model-api.md
> +Each data point can be extracted from different features with varying types, the feature have to be serializable.
Each data point can be extracted from different features with varying types, the features have to be serializable.

2024-08-06 17:57 UTC, jillnogold commented on docs/serving/model-api.md
> +1**Batch Input:**
- **Batch Input:**

2024-08-14 12:53 UTC, jillnogold approved these changes

2024-08-14 18:00 UTC, assaf758 approved these changes

2024-08-14 18:01 UTC, merged