[Docs] Add typical error when updating a function in Nuclio, and not in MLRun
mlrun/mlrun pull request #6116
Opened 2024-08-06 19:34 UTC by jillnogold

[ML-6613](https://iguazio.atlassian.net/issues/ML-6613)

2024-08-07 08:31 UTC, rokatyy commented on docs/concepts/nuclio-real-time-functions.ipynb
> +    "it means that the API gateway was updated at least once manually in Nuclio itself, without using the MLRun SDK.\n",
I think we should propose a solution for the problem as well. And the solution in this case is to delete gw and start from scratch

2024-08-12 13:12 UTC, rokatyy approved these changes

2024-08-12 13:43 UTC, TomerShor requested changes

2024-08-12 13:43 UTC, TomerShor commented on docs/change-log/index.md
> +
remove empty line

2024-08-12 13:43 UTC, TomerShor commented on docs/change-log/index.md
> +
remove empty line

2024-08-15 12:25 UTC, TomerShor approved these changes

2024-08-15 12:25 UTC, merged