[Secretes] If secrets is None delete all secrets data
mlrun/mlrun pull request #6153
Opened 2024-08-11 15:01 UTC by roei3000b

[Here](https://github.com/mlrun/mlrun/blob/30aadb6f3d83b27db15c5704d6c0be0d7503032d/server/api/crud/projects.py#L477) we except that when passing None as the `secrets` that we want to delete, we should delete **all** secrets.
Fixing it this behavior by checking if `secrets` is None and in that case set the `secret_data` to empty dict.

https://iguazio.atlassian.net/browse/ML-7440

2024-08-11 15:50 UTC, alonmr requested changes
Nice! One small change is needed for me to sleep good at night. I know this should never happen but if `k8s_secret.data` is empty than the secret will not be deleted due to if in line 625. If this ever happens we should still delete the secret, otherwise you have to add a secret to be able to completely delete it.

2024-08-11 18:08 UTC, moranbental commented
> Nice! One small change is needed for me to sleep good at night. I know this should never happen but if `k8s_secret.data` is empty than the secret will not be deleted due to if in line 625. If this ever happens we should still delete the secret, otherwise you have to add a secret to be able to completely delete it.

@alonmr Why do we need to check that? We’re already checking it on line 603 and deleting the secret in that case. Additionally, we have test coverage for this on line 134

2024-08-11 18:17 UTC, moranbental requested changes

2024-08-11 18:17 UTC, moranbental commented on server/api/utils/singletons/k8s.py
> +            # Delete all secrets
Please also add to the docstring that when `secret=None`, all secrets are deleted

2024-08-12 07:31 UTC, liranbg approved these changes

2024-08-12 07:32 UTC, moranbental approved these changes
Great!

2024-08-12 11:00 UTC, alonmr approved these changes

2024-08-12 11:00 UTC, merged