[Requirements] Add google cloud dependencies to extra-requirements
mlrun/mlrun pull request #6180
Opened 2024-08-19 08:51 UTC by gtopper

Following #6146.

2024-08-20 11:29 UTC, tomerm-iguazio commented
I was not able to run TestFeatureStoreGoogleBigQuery successfully, can you try to run these tests? @gtopper

2024-08-20 11:55 UTC, gtopper commented
@tomerm-iguazio, I get one failure:
<img width="355" alt="Screenshot 2024-08-20 at 19 54 59" src="https://github.com/user-attachments/assets/f20ed57b-900a-4d44-a829-24cebae6ad9e">
But it's an unrelated issue in development, not something related to this PR.

2024-08-20 15:42 UTC, tomerm-iguazio approved these changes
Looks good:)

2024-08-20 16:57 UTC, tomerm-iguazio requested changes

2024-08-20 16:57 UTC, tomerm-iguazio commented on extras-requirements.txt
> +google-cloud-storage==2.14.0
please make sure your versions do not conflict with [Fix gcs recursive delete](https://github.com/mlrun/mlrun/pull/6193)

2024-08-21 08:28 UTC, tomerm-iguazio approved these changes

2024-08-21 08:34 UTC, merged