[SDK] Fix function name validation
mlrun/mlrun pull request #6188
Opened 2024-08-20 08:50 UTC by adamdelman

[SDK] Fix function name validation when calling the following functions:
|        1. set_function()
|        2. create_model_monitoring_function()
|        3. set_model_monitoring_function

2024-08-21 11:13 UTC, moranbental requested changes
Please add the Jira ticket to the PR description

2024-08-21 11:48 UTC, moranbental requested changes
Looks good! some comments-

2024-08-21 11:48 UTC, moranbental commented on mlrun/projects/project.py
> +                    existing_func_names = []
You don’t need to initialize the list - it is already done later.

2024-08-21 11:48 UTC, moranbental commented on mlrun/projects/project.py
> +                    if not existing_func_defs or func not in existing_func_names:
```suggestion
                    existing_func_names = [existing_func_def.metadata.name for existing_func_def in existing_func_defs]
                    if func not in existing_func_names:
```

2024-08-21 11:48 UTC, moranbental commented on mlrun/projects/project.py
> +            # If name is specified, we try to create a new function with this name.
I suggest moving this comment `# If name is specified, we try to create a new function with this name.` to before line 3439, where the function is actually created.

2024-08-21 11:48 UTC, moranbental commented on mlrun/projects/project.py
> -                raise ValueError("Function name must be specified")
What about raising this error: `raise ValueError("Function name must be specified")`

2024-08-29 07:23 UTC, TomerShor commented
@adamdelman make sure to run `make fmt lint` before you commit your changes

2024-09-08 11:55 UTC, closed without merging