[Docs] Replace old code new_function() with set_function
mlrun/mlrun pull request #6198
Opened 2024-08-22 09:36 UTC by jillnogold

2024-08-25 19:05 UTC, TomerShor requested changes

2024-08-25 19:05 UTC, TomerShor commented on docs/runtimes/serving-function.md
> +serving_fn = mlrun.project.set_function(
```suggestion
serving_fn = project.set_function(
```

2024-08-25 19:05 UTC, TomerShor commented on docs/runtimes/serving-function.md
> +    "serving", kind="serving", image=serving_function_image
```suggestion
    name="serving", kind="serving", image=serving_function_image
```

2024-08-25 19:05 UTC, TomerShor commented on docs/serving/built-in-model-serving.md
> +    "serving", kind="serving", image=serving_function_image
```suggestion
serving_fn = project.set_function(
    name="serving", kind="serving", image=serving_function_image
```

2024-08-25 19:05 UTC, TomerShor commented on docs/runtimes/spark-operator.ipynb
> +    "sj = mlrun.project.set_function(\n",
Also here, pretty sure you need to have a project instance first and not do `mlrun.project`

2024-08-26 08:20 UTC, alonmr requested changes
As Tomer said. You can't use `mlrun.project.set_function` you need a project instance. For example:
```
project = mlrun.get_or_create_project(...)
project.set_function(...)
```

2024-08-26 08:20 UTC, alonmr commented on docs/runtimes/create-and-use-functions.ipynb
> +    "Using the `set_function` method of an MLRun project allows for each of these scenarios in a transparent way. Depending on the source passed in, the project registers the function using some lowe
new_function can still be used in this context. no need to remove

2024-08-26 12:01 UTC, gtopper commented on docs/runtimes/create-and-use-functions.ipynb
> +    "fn = mlrun.project.set_function(name=\"serving\", kind=\"serving\", image=\"mlrun/mlrun\", with_repo=True)\n",
Pretty sure here too, `mlrun.project.set_function` shouldn't be called as if it were a static method.

2024-08-26 12:01 UTC, TomerShor requested changes
Found some more wrong usages of `mlrun.project`.

2024-08-26 12:01 UTC, TomerShor commented on docs/runtimes/spark-operator.ipynb
> +    "sj = mlrun.project.set_function(\n",
```suggestion
    "sj = project.set_function(\n",
```

2024-08-26 12:01 UTC, TomerShor commented on docs/runtimes/create-and-use-functions.ipynb
> +    "fn = mlrun.project.set_function(name=\"serving\", kind=\"serving\", image=\"mlrun/mlrun\", with_repo=True)\n",
```suggestion
    "project = mlrun.get_or_create_project(\"my-project\")\n",
    "fn = project.set_function(name=\"serving\", kind=\"serving\", image=\"mlrun/mlrun\", with_repo=True)\n",
```

2024-08-26 12:01 UTC, TomerShor commented on docs/runtimes/spark-operator.ipynb
> +    "project = mlrun.get_or_create_project(spark - proj)\n",
```suggestion
    "project = mlrun.get_or_create_project(\"spark-proj\")\n",
```

2024-08-26 12:01 UTC, TomerShor commented on docs/serving/model-serving-get-started.ipynb
> +    "fn_preprocess2 = mlrun.project.set_function(\"preprocess\", kind=\"serving\")\n",
```suggestion
    "project = mlrun.get_or_create_project(project_name)\n",
    "fn_preprocess2 = project.set_function(\"preprocess\", kind=\"serving\")\n",
```

2024-08-26 12:01 UTC, TomerShor commented on docs/serving/model-serving-get-started.ipynb
> +    "fn_preprocess2 = mlrun.project.set_function(\"preprocess\", kind=\"serving\")\n",
```suggestion
    "fn_preprocess2 =project.set_function(\"preprocess\", kind=\"serving\")\n",
```

2024-08-27 08:59 UTC, alonmr approved these changes

2024-08-27 10:26 UTC, TomerShor approved these changes

2024-08-27 10:26 UTC, merged