[Alerts] Fix alert triggering for job events by adjusting the sliding window to account for monitoring interval
mlrun/mlrun pull request #6215
Opened 2024-08-27 10:55 UTC by Yacouby

This PR addresses a bug in the alerts flow where alerts configured to trigger based on a specific number of events within a defined period might not trigger correctly when monitoring failed jobs. 
The issue occurred because the monitoring runs flow executes every 30 seconds, which could result in missing the last event in a sequence if it occurs just before the monitoring interval.
so when the monitoring interval is longer than the time gap between the last event and the end of the defined period, the monitoring might miss triggering the alert.

resolves:
https://iguazio.atlassian.net/browse/ML-7549

2024-08-27 12:06 UTC, quaark requested changes
Looks good!
I'd only change the name from interval to offset

2024-08-27 12:06 UTC, quaark commented on server/api/utils/helpers.py
> +def string_to_timedelta(date_str, interval=0, raise_on_error=True):
```suggestion
def string_to_timedelta(date_str, offset=0, raise_on_error=True):
```
a more indicative name IMO

2024-08-28 08:49 UTC, TomerShor commented on server/api/utils/helpers.py
> +def string_to_timedelta(date_str, offset=0, raise_on_error=True):
Add type hints

2024-08-28 10:51 UTC, quaark approved these changes

2024-08-28 10:51 UTC, merged