[Projects] Change the background task timeout for project deletion
mlrun/mlrun pull request #6225
Opened 2024-08-28 11:33 UTC by moranbental

When creating the background task for project deletion, the timeout should be configured using the default value `mlrun.mlconf.background_tasks.default_timeouts.operations.delete_project` from `config.py`, which is set to 15 minutes. However, the background task was hardcoded to wait only 6 minutes. 

The fix is to use the default value from the config to ensure consistency
https://iguazio.atlassian.net/browse/ML-7686

2024-08-28 11:43 UTC, quaark approved these changes
👑

2024-08-28 19:42 UTC, alonmr reviewed
Looks great! minor comment

2024-08-28 19:42 UTC, alonmr commented on server/api/utils/clients/iguazio.py
> +            timeout,
config timeout is a string
```suggestion
            int(timeout),
```

2024-09-01 07:21 UTC, alonmr approved these changes

2024-09-01 07:22 UTC, alonmr requested changes
I think you passed the timeout as error message

2024-09-01 07:22 UTC, alonmr commented on server/api/utils/clients/iguazio.py
> +                mlrun.mlconf.background_tasks.default_timeouts.operations.delete_project,
Actually
```suggestion
                timeout=mlrun.mlconf.background_tasks.default_timeouts.operations.delete_project,
```

2024-09-01 07:29 UTC, alonmr approved these changes

2024-09-01 07:42 UTC, liranbg approved these changes

2024-09-01 11:56 UTC, merged