[Docs] add Additional filters doc
mlrun/mlrun pull request #6234
Opened 2024-08-29 09:11 UTC by tomerm-iguazio

[ML-7690](https://iguazio.atlassian.net/browse/ML-7690)

2024-08-29 11:37 UTC, jond01 commented on docs/feature-store/sources-targets.md
> +```
```suggestion
```py
```

As well as in the other examples

This should also enforce formatting accordingly (`make fmt`/`make lint-docs`)

2024-08-29 13:14 UTC, jillnogold commented on docs/feature-store/sources-targets.md
> +## Parquet source
move entire section just before S3 so it follows the order in the table at the start

2024-08-29 13:51 UTC, jond01 commented on docs/feature-store/sources-targets.md
>      schema= {"id": string, "age": int, "time": pd.Timestamp, ...}
Missing `,`:
```suggestion
    schema= {"id": string, "age": int, "time": pd.Timestamp, ...},
```
Caught only now thanks to marking it as a Python code block

2024-08-31 19:22 UTC, assaf758 requested changes
Looks good in general.
A description of the discrepancy between pandas filtering and pyarrow/parquet (with regard to None / NaN is missing.

2024-09-01 11:53 UTC, jillnogold approved these changes

2024-09-02 08:08 UTC, assaf758 approved these changes

2024-09-02 08:08 UTC, merged