[Docs] Add v1.7 updates to change log
mlrun/mlrun pull request #6260
Opened 2024-09-03 07:21 UTC by jillnogold

2024-10-27 13:08 UTC, roei3000b commented on docs/concepts/notifications.md
@jillnogold , where is my change on [this pr](https://github.com/mlrun/mlrun/pull/6532/files#diff-5788acdc06e77df7d2830bfdc2fbc9a2788a8b2c082ec16fd1a2e0fd731e0cf6)?

2024-10-27 13:19 UTC, moranbental requested changes

2024-10-27 13:19 UTC, moranbental commented on docs/change-log/index.md
> +|ML-2585|When deleting a project, you can also [delete a single artifact](../store/artifacts.html#deleting-artifacts).|
I think ML-2585 should be under the artifact section, not the project section
```suggestion
|ML-2585|When deleting a artifact, you can also [delete a single artifact content](../store/artifacts.html#deleting-artifacts).|
```

2024-10-27 13:19 UTC, moranbental commented on docs/change-log/index.md
> +|ML-7103|UI: New option to show untagged functions in the Functions page (disabled by default). Added time filters to the fFunctions page, by default shows only functions that were modified in the la
```suggestion
|ML-7103|UI: New option to show untagged functions in the Functions page (disabled by default). Added time filters to the Functions page, by default shows only functions that were modified in the last week.|
```

2024-10-27 14:18 UTC, alonmr reviewed
Small comments from me

2024-10-27 14:18 UTC, alonmr commented on docs/change-log/index.md
> +|ML-7568/7915| The SDK does not inform of invalid node selector combinations when running a function, but the pod remains stuck in the Pending state. |See [Preventing and resolving conflicts](../runt
This sounds like an open issue

2024-10-27 14:18 UTC, alonmr commented on docs/change-log/index.md
> +|ML-7673|Improved performance of `db.list_pipelines()` with project filter in environments with a large number of pipelines,|
```suggestion
|ML-7673|Improved performance of `db.list_pipelines()` with project filter in environments with a large number of pipelines.|
```

2024-10-27 14:18 UTC, alonmr commented on docs/change-log/index.md
> +|ML-7706|Fixed the skip `sync_functions` when scheduling workflows or running remote workflows.|
```suggestion
|ML-7706|Change `sync_functions` to be "best effort" when scheduling workflows or running remote workflows.|
```

2024-10-27 14:54 UTC, TomerShor requested changes

2024-10-27 14:54 UTC, TomerShor commented on docs/change-log/index.md
> +|ML-4601|New {ref}`application runtime <application>` where you can run provide an image (for example a web-app) that runs as a deployment. |
```suggestion
|ML-4601|New {ref}`Application runtime <application>` where you can provide an image (a web-app, for example) that runs as a kubernetes deployment. |
```

2024-10-27 14:54 UTC, TomerShor commented on docs/runtimes/configuring-job-resources.md
> +**How to Investigate:
```suggestion
**How to Investigate:**
```

2024-10-28 10:43 UTC, alonmr commented on docs/change-log/index.md
> +|ML-7358|MLRun client now validates certificates by default.|
```suggestion
|ML-7358|MLRun client now validates SSL certificates by default.|
```

2024-10-28 10:43 UTC, alonmr commented on docs/change-log/index.md
> +|ML-3640|When running a remote function/workflow, the `context` global parameter is not automatically injected.| Use `get_or_create_ctx`| v1.3.0    |
The ticket here is closed I think we can remove this one

2024-10-28 10:43 UTC, alonmr commented on docs/change-log/index.md
> +|ML-4857|Local runs can be aborted in the UI, though the actual execution continues.|NA | v1.5.0 |
This is also closed

2024-10-28 10:43 UTC, alonmr commented on docs/change-log/index.md
> +|NL-4881|Kubeflow pipelines parallelism parameter in dsl.ParallelFor() does not work (external dependency). |NA| v1.4.1|
```suggestion
|ML-4881|Kubeflow pipelines parallelism parameter in dsl.ParallelFor() does not work (external dependency). |NA| v1.4.1|
```

2024-10-28 11:13 UTC, alonmr approved these changes
LGTM

2024-10-28 11:23 UTC, TomerShor approved these changes

2024-10-28 11:25 UTC, merged