[Project] Fail sync functions silently on workflow runs
mlrun/mlrun pull request #6308
Opened 2024-09-11 09:35 UTC by alonmr

Sync functions reloads functions that are not neceseraliy related to the workflow, therefore it may fail on issues like file not found for functions that are not needed. This changes sync functions to fail silently when there is a failure to reload a function when trying to run a workflow. If a function fails to load and is later needed in the workflow, it shall be fetched from the DB or fail if it doesn't exist.

https://iguazio.atlassian.net/browse/ML-7706

2024-09-11 10:50 UTC, liranbg requested changes
minor

2024-09-11 10:50 UTC, liranbg commented on mlrun/projects/project.py
> +                    logger.warn(message)
why not abstract the log and move parameters to kwarg? is it possible? I know this warning is for clients but still we need to be consistent with log structure as much as possible

2024-09-11 10:50 UTC, liranbg commented on mlrun/projects/project.py
> +        Reload function objects from specs and files.
worth adding _what_ does it sync and against what (and precedence, etc)

2024-09-11 10:50 UTC, liranbg commented on server/api/db/sqldb/db.py
> +    def _find_labels(self, session, cls, label_cls, labels):
👏🏼

2024-09-11 14:33 UTC, rokatyy reviewed
Minor

2024-09-11 14:33 UTC, rokatyy commented on mlrun/projects/project.py
> +                raise ValueError(f"Function named {name} not found")
```suggestion
            if not function_definition:
                if not silent:
                    raise ValueError(f"Function named {name} not found")
                logger.warn(
                    "Function definition was not found, skipping reload", name=name
                )
```

2024-09-11 14:33 UTC, rokatyy commented on mlrun/projects/project.py
> +                    raise mlrun.errors.MLRunMissingDependencyError(message) from exc
same

2024-09-11 14:33 UTC, rokatyy commented on mlrun/projects/project.py
> +                raise ValueError(message)
same

2024-09-12 07:05 UTC, alonmr commented on mlrun/projects/project.py
> +                raise ValueError(f"Function named {name} not found")
actually I still need to continue because I need to move on to the next function so I kept it as is

2024-09-12 08:27 UTC, rokatyy approved these changes

2024-09-12 14:59 UTC, merged