[Tests] Do not verify SSL by default for system tests.
mlrun/mlrun pull request #6332
Opened 2024-09-15 10:33 UTC by moranbental

2024-09-15 11:01 UTC, alonmr reviewed
Why not add it to env.yml instead? IIRC our CI has an SSL certificate

2024-09-15 11:59 UTC, moranbental commented
> Why not add it to env.yml instead? IIRC our CI has an SSL certificate

I tried that, but it appears we are reading environment variables and updating the config at this line: https://github.com/mlrun/mlrun/blob/f07297b758eca327ecdc4a92a592c831d2ac229a/mlrun/config.py#L1290
Then, when we update dbpath, the first connection is made here: https://github.com/mlrun/mlrun/blob/f07297b758eca327ecdc4a92a592c831d2ac229a/mlrun/config.py#L1104
 As a result, the connection used the default value because the verify setting had not been updated yet

2024-09-16 18:28 UTC, liranbg requested changes

2024-09-16 18:28 UTC, liranbg commented on tests/system/env-template.yml
> +MLRUN_HTTPDB__HTTP__VERIFY:
```suggestion
MLRUN_HTTPDB__HTTP__VERIFY:

```

2024-09-16 18:28 UTC, liranbg commented on tests/system/base.py
> +            os.environ[key] = value
move below callee

2024-09-16 18:28 UTC, liranbg commented on mlrun/config.py
> +        if attr in {"dbpath", "verify"}:
what calls mlconfig.verify now? uncertain why needed then

2024-09-16 18:28 UTC, liranbg commented on mlrun/config.py
> +        _configure_ssl_verification(value)
can u remind why needed?

2024-09-17 05:45 UTC, moranbental commented on mlrun/config.py
> +        if attr in {"dbpath", "verify"}:
When updating the config at this point:
https://github.com/mlrun/mlrun/blob/0e9a5c3e60c96421b43d47dcf560784802c259f0/mlrun/config.py#L1299
the changes will trigger a call to:
https://github.com/mlrun/mlrun/blob/0e9a5c3e60c96421b43d47dcf560784802c259f0/mlrun/config.py#L802

2024-09-17 05:51 UTC, moranbental commented on mlrun/config.py
> +        _configure_ssl_verification(value)
Added a comment

2024-09-18 06:45 UTC, merged