[Notifications] move `override_body` from docs to docstring
mlrun/mlrun pull request #6362
Opened 2024-09-18 11:40 UTC by jillnogold

2024-09-19 07:59 UTC, Yacouby requested changes

2024-09-19 07:59 UTC, Yacouby commented on mlrun/common/schemas/notification.py
> +    body is a dict with the `name`, `message`, `severity`, and the `runs` list of the
```suggestion
    **override_body** - (dict) The body to send with the notification. If not specified, the
    default body will be a dictionary containing `name`, `message`, `severity`, and a `runs` list of the
```

2024-09-19 08:25 UTC, Yacouby approved these changes

2024-09-25 12:46 UTC, assaf758 approved these changes

2024-09-25 12:46 UTC, merged