[Server] Filter permissions correctly when getting project summaries
mlrun/mlrun pull request #6372
Opened 2024-09-19 13:48 UTC by adamdelman

Filter permissions correctly when getting project summaries [ML-7393]
Query OPA using a new resource type "project-summaries"

2024-09-19 14:07 UTC, TomerShor requested changes
Don't forget to run `make fmt lint` before you commit.

2024-09-19 14:07 UTC, TomerShor commented on server/api/api/endpoints/projects.py
> +            ),
if you don't pass a `resource_name`, why not remove it from the template?

2024-09-19 15:19 UTC, alonmr approved these changes
Nice job! LGTM

2024-09-19 15:21 UTC, alonmr commented on server/api/api/endpoints/projects.py
> -    allowed_project_names = projects_output.projects
isn't this line still needed?

2024-09-20 18:22 UTC, liranbg approved these changes

2024-09-20 18:22 UTC, merged