[Docs] Add missing attribute to MLRun-CE Helm chart installation
mlrun/mlrun pull request #6446
Opened 2024-09-29 09:11 UTC by jillnogold

2024-09-29 14:07 UTC, aviaIguazio requested changes
please fix indentation

2024-10-01 16:27 UTC, aviaIguazio requested changes
the indentation is bad
please correct it
    --set global.registry.url=<registry-url> \
    --set global.registry.secretName=registry-credentials \
    --set global.externalHostAddress=<host-machine-address> \
	--set nuclio.dashboard.externalIPAddresses \
change it to	
    --set global.registry.url=<registry-url> \
    --set global.registry.secretName=registry-credentials \
    --set global.externalHostAddress=<host-machine-address> \
    --set nuclio.dashboard.externalIPAddresses \

2024-10-07 06:16 UTC, aviaIguazio approved these changes

2024-10-13 07:51 UTC, liranbg approved these changes

2024-10-13 07:51 UTC, merged