add feature store phase 1
mlrun/mlrun pull request #651
Opened 2021-01-14 00:54 UTC by yaronha

* add feature store model/sdk, ingestion and retrival

2021-01-16 14:06 UTC, Hedingber requested changes
* feature set/feature vector/feature store are all two words, not one, so it should be (file names and variable names) - `feature_store`, `feature_set`, `feature_vector` please fix everywhere
* In a lot of examples (in docstrings) not all variables are defined, please do a pass and make sure everything is defined
* Do a pass and change to use mlrun.errors everywhere

2021-01-16 14:06 UTC, Hedingber commented on tests/feature-store/test_feature_store.py
> +this_dir = f"{tests_root_directory}/feature-store/"
```suggestion
local_dir = f"{tests_root_directory}/feature-store/"
```

2021-01-16 14:06 UTC, Hedingber commented on tests/feature-store/test_infer.py
> +def test_infer():
```suggestion
def test_infer_from_df():
```

2021-01-16 14:08 UTC, yaronha commented on mlrun/featurestore/__init__.py
> +]
i want to only export things that are well documented and useful for users (vs internal)

2021-01-17 15:19 UTC, yaronha commented on mlrun/featurestore/__init__.py
> +from .infer import InferOptions  # noqa
done

2021-01-17 15:23 UTC, yaronha commented on mlrun/featurestore/api.py
> +):
done

2021-01-17 15:26 UTC, yaronha commented on mlrun/featurestore/api.py
> +        raise ValueError("illegal features value/type")
done (for all)

2021-01-17 15:28 UTC, yaronha commented on mlrun/featurestore/api.py
> +    """retrieve offline feature vector
its a common feature store convention/naming (like other frameworks), we dont return the vectors, rather a response w features (and vector object is stored/linked in the resp object)

2021-01-17 15:30 UTC, yaronha commented on mlrun/featurestore/api.py
> +        resp.to_parquet("./out.parquet")
afaik inline examples are not full programs and dont need to include the data or imports

2021-01-17 15:31 UTC, yaronha commented on mlrun/featurestore/api.py
> +        resp.to_parquet("./out.parquet")
i will remove the `fs.` (the function is the one we doc)

2021-01-17 15:35 UTC, yaronha commented on mlrun/featurestore/api.py
> +    controller = init_feature_vector_graph(vector)
it initializes the graph, and returns with the graph controller (it doesnt init the controller)

2021-01-17 16:22 UTC, yaronha commented on mlrun/featurestore/common.py
> +def parse_features(vector):
we can change, was there originally dont remember why i changed

2021-01-17 16:31 UTC, yaronha commented on mlrun/featurestore/common.py
> +    splitted = feature.split(feature_separator)
done

2021-01-17 16:34 UTC, yaronha commented on mlrun/featurestore/infer.py
> +    for column, s in df.items():
`series`, updates

2021-01-17 16:37 UTC, yaronha commented on mlrun/featurestore/ingestion.py
> +    return graph._controller
i dont use it, but i can return graph if it makes u happy :)

2021-01-17 16:40 UTC, yaronha commented on mlrun/featurestore/ingestion.py
> +        runtime = RuntimeKinds.serving if source.online else RuntimeKinds.job
done

2021-01-17 16:47 UTC, yaronha commented on mlrun/featurestore/model/base.py
> +    FeatureVector = "FeatureVector"
removed

2021-01-17 17:40 UTC, yaronha commented on mlrun/featurestore/api.py
> +    """retrieve offline feature vector
fixed doc/text

2021-01-17 17:41 UTC, yaronha commented on mlrun/featurestore/api.py
> +    """initialize and return the feature vector online client
fixed text

2021-01-17 17:41 UTC, yaronha commented on mlrun/featurestore/api.py
> +    :param name:         name to use for the generated feature vector
removed name

2021-01-17 17:46 UTC, yaronha commented on mlrun/featurestore/api.py
> +    controller = init_feature_vector_graph(vector)
done

2021-01-17 17:48 UTC, yaronha commented on mlrun/featurestore/api.py
> +        df = ingest(stocks_set, stocks, infer_options=fs.InferOptions.default())
done (added read_csv)

2021-01-17 17:56 UTC, yaronha commented on mlrun/featurestore/common.py
> +            feature_set_fields[featureset_name] = [(name, alias)]
done

2021-01-17 17:57 UTC, yaronha commented on mlrun/featurestore/common.py
> +def parse_features(vector):
done

2021-01-17 18:12 UTC, yaronha commented on mlrun/featurestore/ingestion.py
> +    return graph._controller
done

2021-01-17 18:18 UTC, yaronha commented on mlrun/featurestore/model/base.py
> +    pass
done

2021-01-17 18:20 UTC, yaronha commented on mlrun/featurestore/model/base.py
> +class DataTargetSpec(ModelObj):
changed to Base

2021-01-17 18:21 UTC, yaronha commented on mlrun/featurestore/model/base.py
> +        hash: str = None,
changed

2021-01-17 18:25 UTC, yaronha commented on mlrun/featurestore/model/featureset.py
> +    def uri(self):
property

2021-01-17 18:26 UTC, yaronha commented on mlrun/featurestore/model/featureset.py
> +                after=after or "$prev",
done

2021-01-17 18:28 UTC, yaronha commented on mlrun/featurestore/model/validators.py
> +    _dict_fields = ["kind", "check_type", "severity", "min", "max"]
done

2021-01-17 18:29 UTC, yaronha commented on mlrun/featurestore/model/validators.py
> +validator_types = {
done

2021-01-17 19:42 UTC, yaronha commented on mlrun/featurestore/sources.py
> +}
added comment

2021-01-17 19:43 UTC, yaronha commented on tests/feature-store/test_feature_store.py
> +this_dir = f"{tests_root_directory}/feature-store/"
done

2021-01-17 19:43 UTC, yaronha commented on tests/feature-store/test_infer.py
> +def test_infer():
done

2021-01-17 20:03 UTC, yaronha commented on mlrun/featurestore/model/datatypes.py
> +def py_to_value_type(value):
done

2021-01-17 20:39 UTC, yaronha commented on mlrun/featurestore/model/base.py
> +store_config = FeatureStoreConfig(copy.deepcopy(default_config))
done, had to add couple of methods to `config`

2021-01-17 20:58 UTC, yaronha commented on mlrun/featurestore/model/vector.py
> +        pass
done

2021-01-18 08:22 UTC, Hedingber approved these changes

2021-01-18 08:22 UTC, merged