[Pagination] Artifacts Pagination Endpoint Support
mlrun/mlrun pull request #6605
Opened 2024-10-30 11:31 UTC by moranbental

This PR modifies the `list_artifacts` endpoint to support pagination by adding the `page`, `page-size`, and `page-token` parameters. Essentially, it implements the pagination mechanism previously established for the initial stage of adding pagination to the `list_runs` and `list_functions` endpoints.

Additionally, it utilizes this mechanism in the SDK by sending a default paginated query, waiting until all responses are received, and returning the complete response at once.

https://iguazio.atlassian.net/browse/ML-8162

2024-10-30 14:46 UTC, TomerShor commented on tests/api/api/test_artifacts.py
> +    tests.api.api.utils.assert_pagination_info(
call with kw args to make it clearer:
```
expected_results_count=..., 
expected_page=..., 
```

2024-10-30 15:50 UTC, rokatyy commented on server/api/crud/artifacts.py
> +        tag: typing.Optional[str] = "",
it's either
```suggestion
        name: typing.Optional[str] = None,
        tag: typing.Optional[str] = None,
```
or as it was before

2024-10-31 07:44 UTC, liranbg requested changes
minor

2024-10-31 07:44 UTC, liranbg commented on server/api/db/sqldb/db.py
> +        page_size: typing.Optional[int] = None,
I think that we need to block requests requesting both limit and page size.
the limit is mainly used by ui to reduce the amount of artifacts they requested. so now that the endpoint is paginated, they could use that instead.
what I suggest is that
if limit is given - use as usual
if limit is given with page size, raise conflict and message should say that page_size and limit are conflicting and only one can be given

2024-11-03 10:00 UTC, liranbg approved these changes

2024-11-03 10:10 UTC, TomerShor approved these changes
LGTM

2024-11-03 11:48 UTC, merged