[Artifacts] Order artifacts by updated date DESC
mlrun/mlrun pull request #6612
Opened 2024-10-31 14:08 UTC by moranbental

When listing artifacts, the order was incorrect: (artifact2, artifact0, artifact4, artifact3, artifact1). 

Added 'ORDER BY updated DESC' to the artifact query to sort by the updated field in descending order. 
This PR also addresses the case when a limit is applied

https://iguazio.atlassian.net/browse/ML-8179

2024-10-31 14:13 UTC, liranbg commented on server/api/db/sqldb/db.py
> +            query = query.order_by(ArtifactV2.updated.desc())
comment _why_ not just _what_

2024-10-31 16:51 UTC, TomerShor requested changes

2024-10-31 16:51 UTC, TomerShor commented on tests/api/api/test_artifacts.py
> +    # Make the request
It's 'Do the request', but anyway you can delete the comment because it's redundant

2024-10-31 16:51 UTC, TomerShor commented on server/api/db/sqldb/db.py
> +        outer_query = outer_query.order_by(ArtifactV2.updated.desc())
If we have limit we already ordered the query, why is this needed again?
Maybe we can order first regardless of the limit?

2024-11-03 09:00 UTC, TomerShor approved these changes

2024-11-03 09:01 UTC, liranbg approved these changes

2024-11-03 09:05 UTC, moranbental commented on server/api/db/sqldb/db.py
> +            query = query.order_by(ArtifactV2.updated.desc())
Added a comment

2024-11-03 09:06 UTC, moranbental commented on server/api/db/sqldb/db.py
> +        outer_query = outer_query.order_by(ArtifactV2.updated.desc())
we need to ensure that the results are ordered after all filtering and joins.
I added a comment

2024-11-03 09:21 UTC, TomerShor commented on tests/api/api/test_artifacts.py
The test is good, but I think it is in the wrong place.
This test file is under the `api` directory, so it should test the functionality of the Artifacts API.
Your changes are in the db layer, so the test fits better in `tests/api/db/test_artifacts.py`, where we test DB-related functionality.

2024-11-03 09:41 UTC, TomerShor requested changes
last thing

2024-11-03 09:41 UTC, TomerShor commented on tests/api/db/test_artifacts.py
> +        expected_count = limit if limit else number_of_artifacts
```suggestion
        expected_count = limit or number_of_artifacts
```

2024-11-03 09:55 UTC, merged