[Workflows] Prevent project fields from being overwritten by remote/scheduled workflows
mlrun/mlrun pull request #6620
Opened 2024-11-03 14:25 UTC by yaelgen

This PR refactors the WorkflowRunners class to enhance code clarity and maintainability by:

Splitting WorkflowRunner into three classes:

BaseRunner: Provides shared functionality.
LoadRunner: Dedicated to project loading.
WorkflowRunners: Focused on workflow execution.
Separating the load_and_run function into two handlers:
project_loader: Loads the project for LoadRunner.
load_and_run_workflow: Loads the project and runs the workflow/schedule - for WorkflowRunners.

Key Changes:

Removed the load_only parameter to simplify logic and avoid conditional statements.
Changed behavior of load_and_run_workflow only for WorkflowRunners:
The function now loads the project without saving it, solely to fetch remote resource files needed by the runner.
It then retrieves the project using get_or_create_project, which gets it from the database if it exists, or creates it from the previously loaded local directory if it doesn't.
This ensures that the runner has access to remote files without overwriting existing project data in the database from the remote project.yaml, and resolves [ML-7801](https://iguazio.atlassian.net/browse/ML-7801).
In the future, we plan to change the PUT behavior of load_project into a PATCH on the client side, and this change will no longer be necessary ([ML-7810](https://iguazio.atlassian.net/browse/ML-7810))

2024-11-04 13:42 UTC, liranbg commented on mlrun/projects/pipelines.py
> -def load_and_run(
add alias function to load_and_run that points to load_and_run_workflow with relevant flags

2024-11-04 20:30 UTC, liranbg commented on mlrun/projects/pipelines.py
> +    load_and_run_workflow(**args)
using the `locals().copy()` is inefficient as you copy all we have here, you can change the function signature to
`def load_and_run(*args, **kwargs):`
and run `kwargs.pop("load_only", None)`

2024-11-04 20:52 UTC, liranbg approved these changes

2024-11-05 08:01 UTC, quaark requested changes
Looks great IMO, I have only a slight naming change I suggest

2024-11-05 08:01 UTC, quaark commented on mlrun/projects/pipelines.py
> +def load_remote_project(
I suggest changing the name of this method (and maybe `project_loader` as well) to be more specific to their goals. 
It's quite confusing trying to track which combination of the words `load` `remote` and `project` result in which kind of functionality, especially since they all eventually call `mlrun.load_project` with different parameters.

I'm thinking maybe:
1. `project_loader` -> `import_remote_project` or `load_remote_project_to_db`
2. `load_remote_project` -> `pull_remote_project_files`

2024-11-06 12:43 UTC, quaark approved these changes
LGTM 🚀

2024-11-06 13:49 UTC, merged