[CI] Add support for running the linter with Python 3.11
mlrun/mlrun pull request #6687
Opened 2024-11-12 07:57 UTC by moranbental

https://iguazio.atlassian.net/browse/ML-7282

2024-11-21 08:16 UTC, adamdelman requested changes

2024-11-21 08:16 UTC, adamdelman commented on Makefile
> +	# TODO: Update format to use py311 for Python 3.11
If we have the python version available in MLRUN_PYTHON_VERSION, why not use that to determine which value gets passed to the `-t` argument?

2024-11-21 08:49 UTC, alonmr commented on Makefile
> +	fi
you can do this in 1-2 liner
see this example
```
# expected to be in the form of '-py<major><minor>' e.g. '-py39'
MLRUN_ANACONDA_PYTHON_DISTRIBUTION := $(shell echo "$(MLRUN_PYTHON_VERSION)" | awk -F. '{print "-py"$$1$$2}')
```
Calculate the env var you need and use it in the command
e.g.
```
MLRUN_LINT_PYTHON_VERSION=... # will be py39 or py311
git ls-files -z -- '*.md' | xargs -0 blacken-docs -t="${MLRUN_LINT_PYTHON_VERSION}" --check;
```

2024-11-21 09:11 UTC, TomerShor requested changes

2024-11-21 09:11 UTC, TomerShor commented on .github/workflows/ci.yaml
> +      run: MLRUN_DOCKER_REGISTRY=ghcr.io/ MLRUN_DOCKER_CACHE_FROM_TAG=${{ steps.docker_cache.outputs.tag }} MLRUN_PYTHON_VERSION=${{ matrix.python-version }} make test-integration-dockerized
Easier to read and extend
```suggestion
      run: |
          MLRUN_DOCKER_REGISTRY=ghcr.io/ \
          MLRUN_DOCKER_CACHE_FROM_TAG=${{ steps.docker_cache.outputs.tag }} \
          MLRUN_PYTHON_VERSION=${{ matrix.python-version }} \
          make test-integration-dockerized
```

2024-11-21 09:11 UTC, TomerShor commented on .github/workflows/ci.yaml
> +        make test-dockerized
The env vars are defined for the same make command, and no as separate commands
```suggestion
      run: |
        MLRUN_DOCKER_REGISTRY=ghcr.io/ \
        MLRUN_DOCKER_CACHE_FROM_TAG=${{ steps.docker_cache.outputs.tag }} \
        MLRUN_PYTHON_VERSION=${{ matrix.python-version }} \
        make test-dockerized
```

2024-11-21 09:11 UTC, TomerShor commented on .github/workflows/docs-language-linter.yaml
> +          python-version: '3.9'  # Use Python 3.9 for link checking
why not 3.11? is there some package that doesn't support it?

2024-11-21 09:11 UTC, TomerShor commented on .github/workflows/docs-language-linter.yaml
> +          make lint-docs
What about `SKIP_VALE_CHECK=true`?

2024-11-21 09:11 UTC, TomerShor commented on .github/workflows/docs-language-linter.yaml
> +          make lint-docs
Also, shouldn't you use the new `MLRUN_LINT_PYTHON_VERSION` env var here?

2024-11-21 10:50 UTC, liranbg commented on .github/workflows/docs-language-linter.yaml
> +        python-version: [ 3.9, 3.11 ]
I think that python 3.9 is enough at this stage

2024-11-21 11:45 UTC, TomerShor commented on .github/workflows/docs-language-linter.yaml
> +        python-version: [ 3.9]
```suggestion
        python-version: [ 3.9 ]
```

2024-11-21 12:54 UTC, TomerShor commented on .github/workflows/ci.yaml
> +        python-version: [ 3.9 ]
actually, I see that we sometimes use quotation and sometimes not (`"3.9"` vs `3.9`). Let's be aligned with that

2024-11-21 14:42 UTC, TomerShor approved these changes

2024-11-28 09:02 UTC, liranbg requested changes

2024-11-28 09:02 UTC, liranbg commented on .github/workflows/docs-language-linter.yaml
> +        python-version: [ "3.9", "3.11" ]
I think the value of having linting docs on both Python versions is currently very small, meaning, docs eventually is going to be either 3.9 or 3.11 but not both. I will leave that for the end, after we move to python 3.11 and because eventually is code is compiled with 3.9 and each strategy takes a runner from github workflow - we can safely remove the 3.11 from the matrix - leaving it to run on python 3.9 only.

2024-11-28 10:30 UTC, merged