[Microservices] Move alert templates to alerts service
mlrun/mlrun pull request #6700
Opened 2024-11-15 13:41 UTC by rokatyy

Move alert templates to alerts service

2024-11-18 10:10 UTC, TomerShor commented on server/py/services/alerts/main.py
@rokatyy @alonmr 
If I understand correctly, if a service is in charge of multiple resources, all of the resources' methods are implemented in the same `Service` class.
In this case, the alerts service is in charge of alert_configs, events, alert_templates and alert_activations, and the `Service` class implements every `store`, `list` etc for each one.

IMO this is not ideal and makes quite a mess and harder to maintain, as opposed to how we had it previously where we had a separate file for each resource.

2024-11-18 11:07 UTC, alonmr commented on server/py/services/alerts/main.py
We can explore separating the endpoints implementation in different ways but this is not part of the MVP so not part of the current considerations. The implementation needs to be service specific as we want separation of responsibilities and concerns. We might want to do something similar as in zebo with resources but again not part of the current effort.

2024-11-18 11:11 UTC, alonmr requested changes
Well done! Minor comments

2024-11-18 11:11 UTC, alonmr commented on server/py/framework/routers/alert_template.py
> +    auth_info: mlrun.common.schemas.AuthInfo = Depends(deps.authenticate_request),
add `request: Request,` it will be needed when the API service will forward requests to alerts service

2024-11-18 11:11 UTC, alonmr commented on server/py/framework/routers/alert_template.py
> +    )
```suggestion
        request,
        auth_info,
        db_session,
    )
```

2024-11-18 11:11 UTC, alonmr commented on server/py/services/alerts/main.py
> +        self.logger.debug("Storing alert template", name=name)
```suggestion
        self._logger.debug("Storing alert template", name=name)
```

2024-11-18 11:11 UTC, alonmr commented on server/py/services/alerts/main.py
> +        self.logger.debug("Deleting alert template", name=name)
same

2024-11-18 11:11 UTC, alonmr commented on server/py/services/alerts/main.py
> +        auth_info: mlrun.common.schemas.AuthInfo,
```suggestion
        request: fastapi.Request,
        auth_info: mlrun.common.schemas.AuthInfo,
```

2024-11-19 10:58 UTC, alonmr approved these changes

2024-11-19 10:58 UTC, merged