[Demos] Fixed the notebook so it would run (not just explaining)
mlrun/mlrun pull request #6707
Opened 2024-11-17 11:40 UTC by EdmondIguazio

2024-11-20 16:01 UTC, gilad-shaham requested changes
Also, markdown still mentions Gemma, we should remove that.
We can add a reference to the end-to-end demo for anyone who would like to dive deeper.

2024-11-20 16:01 UTC, gilad-shaham commented on docs/tutorials/genai-02-model-monitor-llm.ipynb
> +      "3. Use different project context dir.\n"
Let's run it without this issue with project.yaml

2024-11-21 12:06 UTC, gilad-shaham approved these changes

2024-11-24 17:19 UTC, assaf758 approved these changes

2024-11-24 17:19 UTC, merged