[Model monitoring] Add metrics endpoint to httpdb
mlrun/mlrun pull request #6711
Opened 2024-11-17 15:10 UTC by tomerm-iguazio

1) Add `/metrics` endpoint to httpdb.
2) Add wrapper in project to `list_model_endpoints`.

+ test for each feature.

First part of 
[ML-7641](https://iguazio.atlassian.net/browse/ML-7641)

2024-11-17 16:52 UTC, jond01 requested changes

2024-11-17 16:52 UTC, jond01 commented on mlrun/db/httpdb.py
> +            "GET",
Use the enum

2024-11-17 16:52 UTC, jond01 commented on mlrun/db/httpdb.py
> +    ) -> list[mm_endpoints.ModelEndpointMonitoringMetric]:
1. What is returned when there are no metrics?
2. Missing docstring

2024-11-17 16:52 UTC, jond01 commented on tests/system/model_monitoring/test_app.py
> +            "querying httpdb get_model_endpoint_monitoring_metrics", type=type
```suggestion
            "Checking the metrics", type=type
```

2024-11-17 16:52 UTC, jond01 commented on mlrun/projects/project.py
> +        uids: Optional[list[str]] = None,
Nice, though I'm not sure about the defaults of `start` and `end`.
Missing docstring

2024-11-18 09:46 UTC, tomerm-iguazio commented on mlrun/db/httpdb.py
> +    ) -> list[mm_endpoints.ModelEndpointMonitoringMetric]:
1. Fixed to return empty list if there is no result.
2. Added, tnx!

2024-11-18 09:51 UTC, tomerm-iguazio commented on mlrun/projects/project.py
> +        uids: Optional[list[str]] = None,
This is also the default in httpdb.list_model_endpoints, so I did not change it here...

2024-11-18 10:06 UTC, jond01 commented on mlrun/db/httpdb.py
> +        :param project: The name of the project.
A general line on this method can be nice in addition to the params

2024-11-18 10:06 UTC, jond01 commented on mlrun/db/httpdb.py
> +            return []
1. Consider using `pydantic.parse_obj_as`:
   https://stackoverflow.com/a/61021183/27658872
   Just a recommendation, up to you.
2. The if-else is probably unnecessary as `monitoring_metrics = []` returns the expected result.

2024-11-18 10:06 UTC, jond01 commented on server/py/framework/rundb/sqldb.py
>      ):
Can be nice to add the return type

2024-11-18 10:06 UTC, jond01 commented on mlrun/projects/project.py
> +        """
Missing `:return:`

2024-11-18 15:56 UTC, jond01 approved these changes
Great job!

2024-11-19 09:23 UTC, merged