[Alerts] Fix reset alert reason logging
mlrun/mlrun pull request #6776
Opened 2024-11-25 19:16 UTC by Yacouby

Updated the _should_reset_alert method to handle reset policy changes more explicitly. 
Now, the log correctly reports "changes in reset-policy" when the reset is triggered by a change in the alert's reset policy. Additionally, the reset reason logging now specifically reflects individual parameter changes (e.g., "changes in criteria") instead of a generic message when those parameters are modified.

Resolves : 
https://iguazio.atlassian.net/browse/ML-8434

2024-11-25 20:37 UTC, TomerShor requested changes
A general comment - do we really need to log the reason?
It's in the API so it's not visible to the client...

2024-11-25 20:37 UTC, TomerShor commented on server/py/services/alerts/crud/alerts.py
> +                logger.debug("Resetting alert due to %s", reset_reason)
What alert are we resetting?
Also, it's better to use arguments over formatted strings, as the logs stay consistent.
```suggestion
                logger.debug("Resetting alert before storing", project=project, alert_name=name, reason=reset_reason)
```

2024-11-26 06:08 UTC, Yacouby commented
> A general comment - do we really need to log the reason? It's in the API so it's not visible to the client...

it may be good for debugging

2024-11-26 13:33 UTC, TomerShor commented on server/py/services/alerts/crud/alerts.py
>      def _should_reset_alert(old_alert_data, alert_data, force_reset):
Because the function is **should**_reset_alert, I prefer it to still to return (bool, str) with wether it should be reset, and the reason, and not only the reason

2024-11-26 18:03 UTC, TomerShor approved these changes

2024-11-26 18:03 UTC, merged