[Docs] Modify list_runs docstring
mlrun/mlrun pull request #6867
Opened 2024-12-09 09:42 UTC by jillnogold

[ML-8589](https://iguazio.atlassian.net/browse/ML-8589)

2024-12-09 10:07 UTC, theSaarco reviewed
The current description is not completely accurate.

2024-12-09 10:07 UTC, theSaarco commented on mlrun/db/httpdb.py
> +        To get all runs (without the defaults), specify an explicit time using ``start_time_from``.
```suggestion
        To get all runs (without the defaults), specify any filter`.
```
I think this sentence may overall be redundant, since the previous one already explains the logic behind the special case of no-filters.

2024-12-09 10:15 UTC, theSaarco approved these changes
LGTM

2024-12-09 12:07 UTC, moranbental requested changes
What about updating the docstring in the `list_runs` method in `mlrun/projects/project.py`?

2024-12-10 06:46 UTC, jillnogold commented
@moranbental - Is this correct for mlrun/projects/project.py?
"If no filter is provided, it return runs from the last week, partitioned by name."

2024-12-11 06:28 UTC, moranbental requested changes

2024-12-11 06:28 UTC, moranbental commented on mlrun/db/httpdb.py
> +        To get all runs (without the defaults), specify any filter`.
```suggestion
        To get all runs (without the defaults), specify any filter.
```

2024-12-11 18:45 UTC, moranbental approved these changes
LGTM

2024-12-23 09:02 UTC, gtopper approved these changes

2024-12-23 09:02 UTC, merged