[Artifacts] Ensure Each Artifact Has the "Latest" Tag After Migration
mlrun/mlrun pull request #6994
Opened 2024-12-25 12:28 UTC by moranbental

https://iguazio.atlassian.net/browse/ML-8688

2024-12-27 08:35 UTC, liranbg commented on server/py/services/api/initial_data.py
> +    )
that could be huge. why iterating all here and not in chunks?

2024-12-27 08:35 UTC, liranbg commented on server/py/services/api/initial_data.py
> +    artifacts_to_tag = {
could be possible be in a single sql query

2024-12-27 08:35 UTC, liranbg commented on server/py/services/api/initial_data.py
> +        logger.info(f"Adding 'latest' tag to {len(artifacts_to_tag)} artifacts")
id commit in chunks

2024-12-29 19:23 UTC, yaelgen requested changes
Looks really good! Added a suggestion and a question

2024-12-29 19:23 UTC, yaelgen commented on server/py/services/api/tests/unit/test_initial_data.py
> +def test_ensure_latest_tag_for_artifacts():
maybe you can add a summary (was a little confusing for me to follow at first):
```suggestion
Tests `_ensure_latest_tag_for_artifacts` to verify it reassigns the "latest" tag to the most 
recent artifact for each `(project, key, iteration)` combination when tags are missing.

Creates Artifacts:
- `(project1, key1, 0)`: Tags "v1", "v2".
- `(project1, key1, 1)`: Implicitly "latest".
- `(project1, key1, 2)`: Tag "v1".
- `(project2, key1, 0)`: Implicitly "latest".
- `(project2, key2, 0)`: Implicitly "latest".

Steps:
1. Verify initial state: Check 3 "latest"-tagged artifacts for `(project1, key1)`.
2. Remove "latest" from two artifacts and verify only one remains tagged.
3. Run migration with `chunk_size=1`.
4. Verify all 3 artifacts in `(project1, key1)` are correctly retagged as "latest".
```

2024-12-29 19:23 UTC, yaelgen commented on server/py/services/api/initial_data.py
> +            break
Is there a reason to  use `break` here if the loop will terminate when `artifacts_to_tag` is empty? I see we do it above in  `_ensure_function_kind`  as well, just wondered why

2025-01-01 09:34 UTC, liranbg requested changes
very well. minor comment

2025-01-01 09:34 UTC, liranbg commented on server/py/services/api/initial_data.py
> +            "No records to migrate", model=framework.db.sqldb.models.ArtifactV2.Tag
```suggestion
            "No artifacts without 'latest' were found", model=framework.db.sqldb.models.ArtifactV2.Tag
```

2025-01-01 09:34 UTC, liranbg commented on server/py/services/api/initial_data.py
> +        "Starting migration",
```suggestion
        "Starting artifacts without 'latest' tag migration",
```

2025-01-01 09:34 UTC, liranbg commented on server/py/services/api/initial_data.py
> +        "No more records to migrate",
```suggestion
        "No more artifacts to migrate",
```

2025-01-01 09:34 UTC, liranbg commented on server/py/services/api/initial_data.py
> +        model=framework.db.sqldb.models.ArtifactV2.Tag,
```suggestion
```

2025-01-01 10:05 UTC, TomerShor approved these changes
Nice one!

2025-01-01 10:05 UTC, TomerShor commented on server/py/services/api/initial_data.py
> +        sqlalchemy.func.row_number()
remove if unsued

2025-01-01 10:08 UTC, moranbental commented on server/py/services/api/initial_data.py
> +        sqlalchemy.func.row_number()
@TomerShor It is used with `.filter(subquery.c.row_number == 1)`

2025-01-01 13:00 UTC, quaark approved these changes
Great stuff!

2025-01-02 09:25 UTC, yaelgen approved these changes

2025-01-02 11:59 UTC, liranbg approved these changes

2025-01-02 11:59 UTC, merged