RemoteSpark: Added example
mlrun/mlrun pull request #761
Opened 2021-02-22 19:31 UTC by urihoenig

2021-02-22 20:44 UTC, Hedingber requested changes
* Please change the filename to remote-spark.ipynb
* In the title - "Build aSimple Read CSV Function using Spark" you're missing a space in the second word
* I think the spark service name in iguazio systems is always the same, so give in the example this name, so in case someone running the example on iguazio system, it will work for them without changing anything
* @yaronh please review as well, does something need to be done for that to go into the docs ?

2021-02-23 12:12 UTC, yaronha commented
@urihoenig i prefer to change the `with_igz_spark` to `with_spark_service` and make the service provider (igz) a param, which defaults to IGZ

2021-02-23 15:25 UTC, urihoenig commented
@yaronha - Fixed. Can you please approve?

2021-02-23 21:39 UTC, Hedingber approved these changes

2021-02-23 21:41 UTC, merged