Support loading nuclio function from external code entry
mlrun/mlrun pull request #905
Opened 2021-04-29 15:15 UTC by sahare92

2021-05-03 20:23 UTC, yaronha commented on mlrun/runtimes/function.py
> +        """
@sahare92 i dont think the doc string will render ok (e.g. code examples should be idented and after "::", u should check it

2021-05-03 20:23 UTC, yaronha commented on mlrun/runtimes/function.py
> +    ):
use `secrets` for consistency w other calls

2021-05-16 16:36 UTC, Hedingber requested changes

2021-05-16 16:36 UTC, Hedingber commented on mlrun/runtimes/function.py
> +            raise ValueError("Couldn't resolve code entry type from source")
Use `mlrun.errors.MLRunInvalidArgumentError`

2021-05-16 16:36 UTC, Hedingber commented on mlrun/runtimes/function.py
> +            runtime = "python:3.7"
Make configurable (add to `config.py` `default_nuclio_runtime`)

2021-05-16 16:36 UTC, Hedingber commented on mlrun/runtimes/function.py
> +                source = f"http{source[4:]}"
```suggestion
                source = f"http{source[len("v3io"):]}"
```

2021-05-16 16:36 UTC, Hedingber commented on mlrun/runtimes/function.py
> +                raise RuntimeError(f"failed to parse s3 bucket and key. {exc}")
`mlrun.errors.MLRunInvalidArgumentError`

2021-05-16 16:36 UTC, Hedingber commented on mlrun/runtimes/function.py
> +                raise RuntimeError(f"failed to parse s3 bucket and key. {exc}")
Actually, it looks like the only place you're using it, I don't see a reason not raising inside the function itself

2021-05-19 15:53 UTC, Hedingber requested changes
@sahare92 PR looks good, 2 last things:
1. it seems that you have a conflict with upstream
2. @yaronha did some name changes in [his PR](https://github.com/mlrun/mlrun/pull/888) e.g. `with_source_archive` instead of `from_remote_source` - please change accordingly

2021-05-24 11:16 UTC, Hedingber approved these changes

2021-05-24 11:18 UTC, merged